---
title: "PM Component Paper Correlation Plots"
author: "Fatemeh Kazemi"
date: "05-31-2021"
---


```{r}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r Load packages}
  library(tidyverse)
  library(here)
  library(corrplot)
  library(RColorBrewer)
```

```{r Load datasets}
load(here('data','processed', 'pmc-daily.RDa'))
load(here('data','processed', 'pmc-site-ndi.RDa'))
```

```{r}
Para.to.Index <- tribble(
  ~Index, ~Parameter,
   "As", "AS",
   "Ca", "CA",
   "Cu", "CU",
   "Cl", "CL",
   "Fe", "FE",
   "Pb", "PB",
   "Mn", "MN",
   "Ni", "NI",
   "Mg", "MG",
   "Se", "SE",
   "V", "V",
   "Si", "SI",
   "Zn", "ZN",
   "K", "K",
   "Na", "NA",
   "NO3", "NO3",
   "SO4", "SO4",
   "OC", "OC",
   "EC", "EC",
   "PM2.5", "PM"
   ) %>% 
  mutate(Index = as.factor(Index),
         Parameter = as.factor(Parameter))
```

```{r}
dt.pmc <- dt.pmc.daily %>% 
  pivot_longer(cols = AS:PM,
               names_to = "Parameter",
               values_to = "Measurement") %>% 
  merge(Para.to.Index) %>% 
  select(-Parameter) %>% 
  pivot_wider(names_from = "Index",
              values_from = "Measurement",
              names_sort = T)

dt.pmc <- dt.pmc.site.ndi %>% 
  mutate(Loc.Set = ifelse(Location.Setting == "RURAL", "Rural", "Urban"),
         Region = ifelse(Region.IV == 1, "W",
                         ifelse(Region.IV == 2, "MW",
                                ifelse(Region.IV == 3, "S", "NE")))) %>% 
    select(Site.ID, Region, Region.IV, Loc.Set) %>% 
  merge(dt.pmc)

cmp.main.labels <- c("As", "Ca", "Cl", "Cu", "Fe", "K",  "Mg", "Mn", "Na", "Ni",
                     "$NO[3]^'-'", "OC", "Pb", "Se", "Si",
                     "$SO[4]^'2-'", "V", "Zn", "$PM[2.5]")
```

<br>

### US
```{r - US, fig.dim=c(6.5, 6.5)}
corr <- dt.pmc %>%
  select(As,Ca,Cl,Cu,Fe,K,Mg,Mn,Na,Ni,NO3,OC,Pb,Se,Si,SO4,V,Zn,`PM2.5`) %>%
  na.omit %>%
  cor()

colnames(corr) <- cmp.main.labels
rownames(corr) <- cmp.main.labels

jpeg(here('output','plot','corr-us.png'), width = 6.5, height = 6.5, units = 'in',
     res = 300)
corrplot(corr, type = "lower",  method = 'number',
         tl.col = "black", tl.srt = 45, number.cex=0.65, tl.cex = 0.75,
         title = "US",mar=c(0,0,1,0),
         col = rev(brewer.pal(n = 10, name = "RdGy")))
dev.off()
```

<br>

### Regions
```{r - Region, fig.dim=c(6.5, 6.5)}
dt.pmc<-dt.pmc[order(dt.pmc$Region.IV),] %>% 
  mutate(Region = ifelse(Region == "W", "West",
                         ifelse(Region == "MW", "Midwest",
                                ifelse(Region == "S", "South", "Northeast"))))

jpeg(here('output','plot','corr-region.png'), width = 6.5, height = 6.5, units = 'in',
     res = 300)
par(mfrow=c(2,2))
for(i in unique(dt.pmc$Region)) {
  data<- subset(dt.pmc, Region==i)
  corr <- data %>%
    select(As,Ca,Cl,Cu,Fe,K,Mg,Mn,Na,Ni,NO3,OC,Pb,Se,Si,SO4,V,Zn,`PM2.5`) %>%
    na.omit %>%
    cor()
  colnames(corr) <- cmp.main.labels
  rownames(corr) <- cmp.main.labels
  corrplot(corr, type = "lower",
           tl.col = "black", tl.srt = 45, number.cex=0.65, tl.cex = 0.75,
           col = rev(brewer.pal(n = 10, name = "RdGy")), title =i, mar=c(0,0,1,0))
}
dev.off()
```

<br>

### Urbanicity
```{r - Urbanicity, fig.dim=c(6.5,6.5)}
jpeg(here('output','plot','corr-urbanicity.png'), width = 6.5, height = 6.5, units = 'in',
     res = 300)
par(mfrow=c(2,2))
dt.pmc$Loc.Set <- as.factor(dt.pmc$Loc.Set)
dt.pmc$Loc.Set <- relevel(dt.pmc$Loc.Set, ref = "Urban")
dt.pmc <- dt.pmc %>% arrange(Loc.Set)
for(i in unique(dt.pmc$Loc.Set)) {
  data<- subset(dt.pmc, Loc.Set==i)
  corr <- data %>%
    select(As,Ca,Cl,Cu,Fe,K,Mg,Mn,Na,Ni,NO3,OC,Pb,Se,Si,SO4,V,Zn,`PM2.5`) %>%
    na.omit %>%
    cor()
  colnames(corr) <- cmp.main.labels
  rownames(corr) <- cmp.main.labels
  corrplot(corr, type = "lower",
           tl.col = "black", tl.srt = 45, number.cex=0.65, tl.cex = 0.75,
           col = rev(brewer.pal(n = 10, name = "RdGy")), title =i, mar=c(0,0,1,0)) 
}
dev.off()
```
