---
title: "Config File Generator"
output: 
---

### This program:
  (1) Generates configuration files for Java for different combinations of 
      i. pollutant
      ii. cause of death
      iii. model

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages}
library(tidyverse)
library(here)
```

```{r List of PM Components}
pmc <- c("Yr_AS","Yr_CA","Yr_CL","Yr_CU","Yr_EC","Yr_FE","Yr_K",
       "Yr_MG","Yr_MN","Yr_NA","Yr_NI","Yr_NO3","Yr_OC","Yr_PB",
       "Yr_PM","Yr_SE","Yr_SI","Yr_SO4","Yr_V","Yr_ZN")
```

```{r List of Factors}
fac <- c("Factor1","Factor2","Factor3","Factor4",
         "Factor5","Factor6","Factor7","Factor8")
```

```{r List of PM Components Residuals}
pmcres <- c("PM_SE","PM_CA","PM_CL","PM_NA","PM_NI","PM_NO3",
            "PM_OC","PM_PB","PM_SI","PM_SO4","PM_V","PM_ZN")
```

```{r List of Factors Residuals}
facres <- c("PM_Factor1","PM_Factor2","PM_Factor3","PM_Factor4",
            "PM_Factor5","PM_Factor6","PM_Factor7","PM_Factor8")
```

```{r List of Carbons}
carbon <- c("Yr_EC", "Yr_OC")
```

```{r List of PM Components Sub}
pmc.sub <- c("SE","CA","CL","NA","NI","NO3","OC",
             "PB","PM","SI","SO4","V","ZN")
```

```{r List of PM Components Yr Sub}
pmc.sub.yr <- c("Yr_SE","Yr_CA","Yr_CL","Yr_NA","Yr_NI","Yr_NO3","Yr_OC",
             "Yr_PB","Yr_PM","Yr_SI","Yr_SO4","Yr_V","Yr_ZN")
```

```{r List of Causes of Death}
cuz <- c("allcuz","nacc","acc","cvd","ihd","chf","cbv","resp","copd","pneu","canc","lungc")
```

```{r List of Causes of Death}
cuz.sub <- c("allcuz","cvd","ihd","chf","cbv","resp","copd","pneu","canc","lungc")
```

```{r Config file - Base Model}
config.base <- c("# data path
data_path=/scratch/fatemehkp/projects/data/analysis/dataset

# loader settings
# separated symbol for the given data
sep=,
# the predictors are included in the model
predictors=exposure
# stratas
stratas=StrID, SiteID
# death
death=no_death_outcome
# life
life=no_enrollee

# optimizer settings
# whether considering ties for death, default false
isTies=false
# if given multiple cores, set isParallelism as true
isParallelism=true
# whether penalizing the weight
l2=false
# if penalizing the weight, set the strength, otherwise it is useless.
l2Strength=1

# the application class name
survival.class=CoxPH
")
```

```{r Config file - SES Adj. Model}
config.ses <- c("# data path
data_path=/scratch/fatemehkp/projects/data/analysis/dataset

# loader settings
# separated symbol for the given data
sep=,
# the predictors are included in the model
predictors=exposure, ses
# stratas
stratas=StrID, SiteID
# death
death=no_death_outcome
# life
life=no_enrollee

# optimizer settings
# whether considering ties for death, default false
isTies=false
# if given multiple cores, set isParallelism as true
isParallelism=true
# whether penalizing the weight
l2=false
# if penalizing the weight, set the strength, otherwise it is useless.
l2Strength=1

# the application class name
survival.class=CoxPH
")
```

```{r Config file - EM Models}
config.em <- c("# data path
data_path=/scratch/fatemehkp/projects/data/analysis/dataset

# loader settings
# separated symbol for the given data
sep=,
# the predictors are included in the model
predictors=Yr_exposure, subg, subg_exposure, ses
# stratas
stratas=StrID, SiteID
# death
death=no_death_outcome
# life
life=no_enrollee

# optimizer settings
# whether considering ties for death, default false
isTies=false
# if given multiple cores, set isParallelism as true
isParallelism=true
# whether penalizing the weight
l2=false
# if penalizing the weight, set the strength, otherwise it is useless.
l2Strength=1

# the application class name
survival.class=CoxPH
")
```

```{r Config file - EM Models 2}
config.em.2 <- c("# data path
data_path=/scratch/fatemehkp/projects/data/analysis/dataset

# loader settings
# separated symbol for the given data
sep=,
# the predictors are included in the model
predictors=exposure, subg, subg_exposure, ses
# stratas
stratas=StrID, SiteID
# death
death=no_death_outcome
# life
life=no_enrollee

# optimizer settings
# whether considering ties for death, default false
isTies=false
# if given multiple cores, set isParallelism as true
isParallelism=true
# whether penalizing the weight
l2=false
# if penalizing the weight, set the strength, otherwise it is useless.
l2Strength=1

# the application class name
survival.class=CoxPH
")
```

```{r Config file - BRFSS Models}
config.brfss <- c("# data path
data_path=/scratch/fatemehkp/projects/data/analysis/dataset

# loader settings
# separated symbol for the given data
sep=,
# the predictors are included in the model
predictors=exposure, ses, BMI, Race, Smoke, Diabt, Asthma, Drink
# stratas
stratas=StrID, SiteID
# death
death=no_death_outcome
# life
life=no_enrollee

# optimizer settings
# whether considering ties for death, default false
isTies=false
# if given multiple cores, set isParallelism as true
isParallelism=true
# whether penalizing the weight
l2=false
# if penalizing the weight, set the strength, otherwise it is useless.
l2Strength=1

# the application class name
survival.class=CoxPH
")
```


```{r base model for components}
dataname <- "ndi-pmc.csv"
expo <- pmc

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.base, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    for (j in seq(1,length(cuz),1)){
      w <- gsub("outcome", cuz[j], z)
      cat(w, file=f, sep="\n")
      k=j+length(cuz)*(i-1)
      writeLines(w, here('config-files','pmc-base', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```

```{r ses adj. model for components}
dataname <- "ndi-pmc.csv"
expo <- pmc

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.ses, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    for (j in seq(1,length(cuz),1)){
      w <- gsub("outcome", cuz[j], z)
      cat(w, file=f, sep="\n")
      k=j+length(cuz)*(i-1)
      writeLines(w, here('config-files','pmc-ses', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```

```{r base model for factors}
dataname <- "ndi-fac.csv"
expo <- fac

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.base, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    for (j in seq(1,length(cuz),1)){
      w <- gsub("outcome", cuz[j], z)
      cat(w, file=f, sep="\n")
      k=j+length(cuz)*(i-1)
      writeLines(w, here('config-files','fac-base', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```

```{r ses adj. model for factors}
dataname <- "ndi-fac.csv"
expo <- fac

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.ses, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    for (j in seq(1,length(cuz),1)){
      w <- gsub("outcome", cuz[j], z)
      cat(w, file=f, sep="\n")
      k=j+length(cuz)*(i-1)
      writeLines(w, here('config-files','fac-ses', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```

```{r base model for factors excluding EC}
dataname <- "ndi-fac-ex-ec.csv"
expo <- fac

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.base, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    for (j in seq(1,length(cuz),1)){
      w <- gsub("outcome", cuz[j], z)
      cat(w, file=f, sep="\n")
      k=j+length(cuz)*(i-1)
      writeLines(w, here('config-files','fac-ex-ec-base', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```

```{r ses adj. model for factors excluding EC}
dataname <- "ndi-fac-ex-ec.csv"
expo <- fac

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.ses, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    for (j in seq(1,length(cuz),1)){
      w <- gsub("outcome", cuz[j], z)
      cat(w, file=f, sep="\n")
      k=j+length(cuz)*(i-1)
      writeLines(w, here('config-files','fac-ex-ec-ses', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```

```{r ses adj. model for TOT Carbons}
dataname <- "ndi-carbon-tot.csv"
expo <- carbon

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.ses, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    for (j in seq(1,length(cuz),1)){
      w <- gsub("outcome", cuz[j], z)
      cat(w, file=f, sep="\n")
      k=j+length(cuz)*(i-1)
      writeLines(w, here('config-files','tot-ses', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```

```{r ses adj. model for TOR Carbons}
dataname <- "ndi-carbon-tor.csv"
expo <- carbon

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.ses, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    for (j in seq(1,length(cuz),1)){
      w <- gsub("outcome", cuz[j], z)
      cat(w, file=f, sep="\n")
      k=j+length(cuz)*(i-1)
      writeLines(w, here('config-files','tor-ses', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```

```{r ses adj. model for components residuals}
dataname <- "ndi-pmc-residual.csv"
expo <- pmcres

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.ses, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    for (j in seq(1,length(cuz),1)){
      w <- gsub("outcome", cuz[j], z)
      cat(w, file=f, sep="\n")
      k=j+length(cuz)*(i-1)
      writeLines(w, here('config-files','pmc-resid', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```

```{r ses adj. model for factors excluding EC Residual}
dataname <- "ndi-fac-ex-ec-residual.csv"
expo <- facres

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.ses, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    for (j in seq(1,length(cuz),1)){
      w <- gsub("outcome", cuz[j], z)
      cat(w, file=f, sep="\n")
      k=j+length(cuz)*(i-1)
      writeLines(w, here('config-files','fac-resid', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```

```{r ses adj. model for components - race Asian}
dataname <- "ndi-pmc-raceA.csv"
expo <- pmc.sub
subg <- "rA"

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.em, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    s <- gsub("subg", subg, z)
    for (j in seq(1,length(cuz),1)){
      w <- gsub("outcome", cuz[j], s)
      cat(w, file=f, sep="\n")
      k=j+length(cuz)*(i-1)
      writeLines(w, here('config-files','pmc-race-A', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```

```{r ses adj. model for components - race Black}
dataname <- "ndi-pmc-raceB.csv"
expo <- pmc.sub
subg <- "rB"

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.em, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    s <- gsub("subg", subg, z)
    for (j in seq(1,length(cuz),1)){
      w <- gsub("outcome", cuz[j], s)
      cat(w, file=f, sep="\n")
      k=j+length(cuz)*(i-1)
      writeLines(w, here('config-files','pmc-race-B', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```

```{r ses adj. model for components - race Hispanic}
dataname <- "ndi-pmc-raceH.csv"
expo <- pmc.sub
subg <- "rH"

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.em, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    s <- gsub("subg", subg, z)
    for (j in seq(1,length(cuz),1)){
      w <- gsub("outcome", cuz[j], s)
      cat(w, file=f, sep="\n")
      k=j+length(cuz)*(i-1)
      writeLines(w, here('config-files','pmc-race-H', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```

```{r ses adj. model for components - race White}
dataname <- "ndi-pmc-raceW.csv"
expo <- pmc.sub
subg <- "rW"

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.em, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    s <- gsub("subg", subg, z)
    for (j in seq(1,length(cuz),1)){
      w <- gsub("outcome", cuz[j], s)
      cat(w, file=f, sep="\n")
      k=j+length(cuz)*(i-1)
      writeLines(w, here('config-files','pmc-race-W', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```

```{r ses adj. model for factors - age LE75}
dataname <- "ndi-fac-ageLE75.csv"
expo <- fac
subg <- "aLE75"

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.em.2, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    s <- gsub("subg", subg, z)
    for (j in seq(1,length(cuz.sub),1)){
      w <- gsub("outcome", cuz.sub[j], s)
      cat(w, file=f, sep="\n")
      k=j+length(cuz.sub)*(i-1)
      writeLines(w, here('config-files','fac-ageLE75', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```

```{r ses adj. model for factors - race Asian}
dataname <- "ndi-fac-raceA.csv"
expo <- fac
subg <- "rA"

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.em.2, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    s <- gsub("subg", subg, z)
    for (j in seq(1,length(cuz),1)){
      w <- gsub("outcome", cuz[j], s)
      cat(w, file=f, sep="\n")
      k=j+length(cuz)*(i-1)
      writeLines(w, here('config-files','fac-race-A', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```

```{r ses adj. model for factors - race Black}
dataname <- "ndi-fac-raceB.csv"
expo <- fac
subg <- "rB"

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.em.2, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    s <- gsub("subg", subg, z)
    for (j in seq(1,length(cuz),1)){
      w <- gsub("outcome", cuz[j], s)
      cat(w, file=f, sep="\n")
      k=j+length(cuz)*(i-1)
      writeLines(w, here('config-files','fac-race-B', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```

```{r ses adj. model for factors - race Hispanic}
dataname <- "ndi-fac-raceH.csv"
expo <- fac
subg <- "rH"

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.em.2, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    s <- gsub("subg", subg, z)
    for (j in seq(1,length(cuz),1)){
      w <- gsub("outcome", cuz[j], s)
      cat(w, file=f, sep="\n")
      k=j+length(cuz)*(i-1)
      writeLines(w, here('config-files','fac-race-H', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```

```{r ses adj. model for factors - race White}
dataname <- "ndi-fac-raceW.csv"
expo <- fac
subg <- "rW"

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.em.2, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    s <- gsub("subg", subg, z)
    for (j in seq(1,length(cuz),1)){
      w <- gsub("outcome", cuz[j], s)
      cat(w, file=f, sep="\n")
      k=j+length(cuz)*(i-1)
      writeLines(w, here('config-files','fac-race-W', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```

```{r ses adj. model for components - Urban}
dataname <- "ndi-pmc-urban.csv"
expo <- pmc.sub
subg <- "urb"

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.em, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    s <- gsub("subg", subg, z)
    for (j in seq(1,length(cuz),1)){
      w <- gsub("outcome", cuz[j], s)
      cat(w, file=f, sep="\n")
      k=j+length(cuz)*(i-1)
      writeLines(w, here('config-files','pmc-urban', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```

```{r ses adj. model for components - Rural}
dataname <- "ndi-pmc-rural.csv"
expo <- pmc.sub
subg <- "rur"

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.em, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    s <- gsub("subg", subg, z)
    for (j in seq(1,length(cuz),1)){
      w <- gsub("outcome", cuz[j], s)
      cat(w, file=f, sep="\n")
      k=j+length(cuz)*(i-1)
      writeLines(w, here('config-files','pmc-rural', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```


```{r ses adj. model for components - Urban ses Low}
dataname <- "ndi-pmc-urban-sesL.csv"
expo <- pmc.sub
subg <- "sesL"

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.em, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    s <- gsub("subg", subg, z)
    for (j in seq(1,length(cuz),1)){
      w <- gsub("outcome", cuz[j], s)
      cat(w, file=f, sep="\n")
      k=j+length(cuz)*(i-1)
      writeLines(w, here('config-files','pmc-urban-sesL', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```


```{r ses adj. model for components - Urban ses Middle}
dataname <- "ndi-pmc-urban-sesM.csv"
expo <- pmc.sub
subg <- "sesM"

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.em, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    s <- gsub("subg", subg, z)
    for (j in seq(1,length(cuz),1)){
      w <- gsub("outcome", cuz[j], s)
      cat(w, file=f, sep="\n")
      k=j+length(cuz)*(i-1)
      writeLines(w, here('config-files','pmc-urban-sesM', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```


```{r ses adj. model for components - Urban ses High}
dataname <- "ndi-pmc-urban-sesH.csv"
expo <- pmc.sub
subg <- "sesH"

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.em, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    s <- gsub("subg", subg, z)
    for (j in seq(1,length(cuz),1)){
      w <- gsub("outcome", cuz[j], s)
      cat(w, file=f, sep="\n")
      k=j+length(cuz)*(i-1)
      writeLines(w, here('config-files','pmc-urban-sesH', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```

```{r ses adj. model for components - West}
dataname <- "ndi-pmc-west.csv"
expo <- pmc.sub
subg <- "rW"

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.em, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    s <- gsub("subg", subg, z)
    for (j in seq(1,length(cuz),1)){
      w <- gsub("outcome", cuz[j], s)
      cat(w, file=f, sep="\n")
      k=j+length(cuz)*(i-1)
      writeLines(w, here('config-files','pmc-west', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```

```{r ses adj. model for components - Midwest}
dataname <- "ndi-pmc-midwest.csv"
expo <- pmc.sub
subg <- "rMW"

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.em, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    s <- gsub("subg", subg, z)
    for (j in seq(1,length(cuz),1)){
      w <- gsub("outcome", cuz[j], s)
      cat(w, file=f, sep="\n")
      k=j+length(cuz)*(i-1)
      writeLines(w, here('config-files','pmc-midwest', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```

```{r ses adj. model for components - South}
dataname <- "ndi-pmc-south.csv"
expo <- pmc.sub
subg <- "rS"

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.em, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    s <- gsub("subg", subg, z)
    for (j in seq(1,length(cuz),1)){
      w <- gsub("outcome", cuz[j], s)
      cat(w, file=f, sep="\n")
      k=j+length(cuz)*(i-1)
      writeLines(w, here('config-files','pmc-south', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```

```{r ses adj. model for components - Northeast}
dataname <- "ndi-pmc-northeast.csv"
expo <- pmc.sub
subg <- "rNE"

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.em, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    s <- gsub("subg", subg, z)
    for (j in seq(1,length(cuz),1)){
      w <- gsub("outcome", cuz[j], s)
      cat(w, file=f, sep="\n")
      k=j+length(cuz)*(i-1)
      writeLines(w, here('config-files','pmc-northeast', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```

```{r ses adj. model for components - Age LE75}
dataname <- "ndi-pmc-ageLE75.csv"
expo <- pmc.sub
subg <- "aLE75"

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.em, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    s <- gsub("subg", subg, z)
    for (j in seq(1,length(cuz),1)){
      w <- gsub("outcome", cuz[j], s)
      cat(w, file=f, sep="\n")
      k=j+length(cuz)*(i-1)
      writeLines(w, here('config-files','pmc-ageLE75', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```

```{r ses adj. model for components - Age M75}
dataname <- "ndi-pmc-ageM75.csv"
expo <- pmc.sub
subg <- "aM75"

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.em, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    s <- gsub("subg", subg, z)
    for (j in seq(1,length(cuz),1)){
      w <- gsub("outcome", cuz[j], s)
      cat(w, file=f, sep="\n")
      k=j+length(cuz)*(i-1)
      writeLines(w, here('config-files','pmc-ageM75', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```

```{r ses adj. model for factors - age LE75}
dataname <- "ndi-fac-ageLE75.csv"
expo <- fac
subg <- "aLE75"

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.em.2, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    s <- gsub("subg", subg, z)
    for (j in seq(1,length(cuz.sub),1)){
      w <- gsub("outcome", cuz.sub[j], s)
      cat(w, file=f, sep="\n")
      k=j+length(cuz.sub)*(i-1)
      writeLines(w, here('config-files','fac-ageLE75', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```

```{r ses adj. model for factors - age M75}
dataname <- "ndi-fac-ageM75.csv"
expo <- fac
subg <- "aM75"

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.em.2, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    s <- gsub("subg", subg, z)
    for (j in seq(1,length(cuz.sub),1)){
      w <- gsub("outcome", cuz.sub[j], s)
      cat(w, file=f, sep="\n")
      k=j+length(cuz.sub)*(i-1)
      writeLines(w, here('config-files','fac-ageM75', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```

```{r ses adj. model for components - Female}
dataname <- "ndi-pmc-sexF.csv"
expo <- pmc.sub
subg <- "sexF"

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.em, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    s <- gsub("subg", subg, z)
    for (j in seq(1,length(cuz),1)){
      w <- gsub("outcome", cuz[j], s)
      cat(w, file=f, sep="\n")
      k=j+length(cuz)*(i-1)
      writeLines(w, here('config-files','pmc-sexF', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```

```{r ses adj. model for components - Male}
dataname <- "ndi-pmc-sexM.csv"
expo <- pmc.sub
subg <- "sexM"

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.em, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    s <- gsub("subg", subg, z)
    for (j in seq(1,length(cuz),1)){
      w <- gsub("outcome", cuz[j], s)
      cat(w, file=f, sep="\n")
      k=j+length(cuz)*(i-1)
      writeLines(w, here('config-files','pmc-sexM', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```

```{r ses adj. model for factors - sex F}
dataname <- "ndi-fac-sexF.csv"
expo <- fac
subg <- "sexF"

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.em.2, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    s <- gsub("subg", subg, z)
    for (j in seq(1,length(cuz.sub),1)){
      w <- gsub("outcome", cuz.sub[j], s)
      cat(w, file=f, sep="\n")
      k=j+length(cuz.sub)*(i-1)
      writeLines(w, here('config-files','fac-sexF', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```

```{r ses adj. model for factors - sex M}
dataname <- "ndi-fac-sexM.csv"
expo <- fac
subg <- "sexM"

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.em.2, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    s <- gsub("subg", subg, z)
    for (j in seq(1,length(cuz.sub),1)){
      w <- gsub("outcome", cuz.sub[j], s)
      cat(w, file=f, sep="\n")
      k=j+length(cuz.sub)*(i-1)
      writeLines(w, here('config-files','fac-sexM', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```

```{r ses adj. model for components - sites with BRFSS data}
dataname <- "ndi-pmc-brfss.csv"
expo <- pmc.sub.yr

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.ses, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    for (j in seq(1,length(cuz),1)){
      w <- gsub("outcome", cuz[j], z)
      cat(w, file=f, sep="\n")
      k=j+length(cuz)*(i-1)
      writeLines(w, here('config-files','pmc-brfss-0', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```

```{r ses adj. model for components - adj. BRFSS data}
dataname <- "ndi-pmc-brfss.csv"
expo <- pmc.sub.yr

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.brfss, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    for (j in seq(1,length(cuz),1)){
      w <- gsub("outcome", cuz[j], z)
      cat(w, file=f, sep="\n")
      k=j+length(cuz)*(i-1)
      writeLines(w, here('config-files','pmc-brfss', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```



```{r ses adj. model for components - 5yr}
dataname <- "ndi-pmc-5yr.csv"
expo <- pmc.sub.yr

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.ses, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    for (j in seq(1,length(cuz),1)){
      w <- gsub("outcome", cuz[j], z)
      cat(w, file=f, sep="\n")
      k=j+length(cuz)*(i-1)
      writeLines(w, here('config-files','pmc-5yr', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```

```{r ses adj. model for components - 4yr-5yr}
dataname <- "ndi-pmc-4yr-5yr.csv"
expo <- pmc.sub.yr

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.ses, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    for (j in seq(1,length(cuz),1)){
      w <- gsub("outcome", cuz[j], z)
      cat(w, file=f, sep="\n")
      k=j+length(cuz)*(i-1)
      writeLines(w, here('config-files','pmc-4yr', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```

```{r ses adj. model for components - 3yr-5yr}
dataname <- "ndi-pmc-3yr-5yr.csv"
expo <- pmc.sub.yr

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.ses, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    for (j in seq(1,length(cuz),1)){
      w <- gsub("outcome", cuz[j], z)
      cat(w, file=f, sep="\n")
      k=j+length(cuz)*(i-1)
      writeLines(w, here('config-files','pmc-3yr', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```

```{r ses adj. model for components - 2yr-5yr}
dataname <- "ndi-pmc-2yr-5yr.csv"
expo <- pmc.sub.yr

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.ses, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    for (j in seq(1,length(cuz),1)){
      w <- gsub("outcome", cuz[j], z)
      cat(w, file=f, sep="\n")
      k=j+length(cuz)*(i-1)
      writeLines(w, here('config-files','pmc-2yr', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```

```{r ses adj. model for components - 1yr-5yr}
dataname <- "ndi-pmc-1yr-5yr.csv"
expo <- pmc.sub.yr

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.ses, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    for (j in seq(1,length(cuz),1)){
      w <- gsub("outcome", cuz[j], z)
      cat(w, file=f, sep="\n")
      k=j+length(cuz)*(i-1)
      writeLines(w, here('config-files','pmc-1yr', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```

```{r ses adj. model for components - bz 6}
dataname <- "ndi-pmc-bz6.csv"
expo <- pmc.sub.yr

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.ses, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    for (j in seq(1,length(cuz),1)){
      w <- gsub("outcome", cuz[j], z)
      cat(w, file=f, sep="\n")
      k=j+length(cuz)*(i-1)
      writeLines(w, here('config-files','pmc-bz6', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```

```{r ses adj. model for components - bz 12}
dataname <- "ndi-pmc-bz12.csv"
expo <- pmc.sub.yr

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.ses, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    for (j in seq(1,length(cuz),1)){
      w <- gsub("outcome", cuz[j], z)
      cat(w, file=f, sep="\n")
      k=j+length(cuz)*(i-1)
      writeLines(w, here('config-files','pmc-bz12', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```

```{r ses adj. model for components - bz 24}
dataname <- "ndi-pmc-bz24.csv"
expo <- pmc.sub.yr

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.ses, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    for (j in seq(1,length(cuz),1)){
      w <- gsub("outcome", cuz[j], z)
      cat(w, file=f, sep="\n")
      k=j+length(cuz)*(i-1)
      writeLines(w, here('config-files','pmc-bz24', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```

```{r ses adj. model for components residuals - West}
dataname <- "ndi-pmc-res-west.csv"
expo <- pmcres
subg <- "rW"

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.em.2, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    s <- gsub("subg", subg, z)
    for (j in seq(1,length(cuz.sub),1)){
      w <- gsub("outcome", cuz.sub[j], s)
      cat(w, file=f, sep="\n")
      k=j+length(cuz.sub)*(i-1)
      writeLines(w, here('config-files','pmc-resid-west', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```

```{r ses adj. model for components residuals - Midwest}
dataname <- "ndi-pmc-res-midwest.csv"
expo <- pmcres
subg <- "rMW"

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.em.2, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    s <- gsub("subg", subg, z)
    for (j in seq(1,length(cuz.sub),1)){
      w <- gsub("outcome", cuz.sub[j], s)
      cat(w, file=f, sep="\n")
      k=j+length(cuz.sub)*(i-1)
      writeLines(w, here('config-files','pmc-resid-midwest', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```

```{r ses adj. model for components residuals - South}
dataname <- "ndi-pmc-res-south.csv"
expo <- pmcres
subg <- "rS"

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.em.2, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    s <- gsub("subg", subg, z)
    for (j in seq(1,length(cuz.sub),1)){
      w <- gsub("outcome", cuz.sub[j], s)
      cat(w, file=f, sep="\n")
      k=j+length(cuz.sub)*(i-1)
      writeLines(w, here('config-files','pmc-resid-South', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```

```{r ses adj. model for components residuals - Northeast}
dataname <- "ndi-pmc-res-northeast.csv"
expo <- pmcres
subg <- "rNE"

for (i in seq(1,length(expo),1)){
  filenames <- c( tempfile())
  for( f in  filenames ){
    cat(config.em.2, file=f)
    x <- readLines(f)
    y <- gsub("dataset", dataname, x)
    z <- gsub("exposure", expo[i], y)
    s <- gsub("subg", subg, z)
    for (j in seq(1,length(cuz.sub),1)){
      w <- gsub("outcome", cuz.sub[j], s)
      cat(w, file=f, sep="\n")
      k=j+length(cuz.sub)*(i-1)
      writeLines(w, here('config-files','pmc-resid-northeast', paste(k,'.txt', sep = "")))
    }
  }
  file.remove(f)
  }
```


```{r under work - parse output}
result = matrix(nrow=1,ncol=4,byrow = TRUE) 
colnames(result) <- c("Expo","Outcome","Beta","SE")

for (i in seq(1,240,1)){
  test <- readLines(here('output','85.txt'))
  important_line2 <- test[min(grep("^death", test))]
  dt <- dt %>% 
    mutate(cuz = gsub(".*death_", "", important_line2))
  important_line <- test[min(grep("^Factor", test))]
  Expo <- gsub("\t.*", "", important_line)
  Coef <- sub(".*\t(.*)\t.*","\\1", important_line)
  SE <- gsub(".*\t", "", important_line)
}

```