---
title: "Air Quality Data from EPA AQS"
author: "Fatemeh Kazemi"
date: "10-06-2021"
output:
  html_document:
    df_print: paged
---

### This program:
  (1) Run factor analysis
  
# Notes
  1. Combination2 is better for mass app

```{r}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r load packages}
  library(tidyverse)
  library(here)
  library(psych) # for factor analysis
  library(lme4) # mixed model
  library(sjPlot) # tab_model
```

```{r Load datasets}
load(here('data','processed', 'pmc-daily.RDa'))
load(here('data','processed', 'aqs-sites.RDa'))
#load(here('data','processed', 'mass-apportioned-c1.RDa'))
```

```{r Call functions}
source(here('code','data-processors','air-data-smooth-mvavg-function.R'))

so.coef <- function(model, cmp){
  source = as.numeric(summary(model)$coefficients[,1][cmp])
  return(source)
}
```

```{r - preliminary factor analysis}
# All eligible monitors
fit <- factanal(dt.pmc.daily %>% select(AS:OC), 8, rotation="varimax")
factor.loadings.ec <- rbind(fit$loadings)
save(factor.loadings.ec, file = here('output','table','factor-loadings-ec.RDa'))
#Traffic Soil Metals Biomass Salt Oil Coal Steel

factor.scores <- factor.scores(dt.pmc.daily %>% select(AS:OC), fit)
dt.fac.ec.daily <- cbind(dt.pmc.daily %>% select(Site.ID, Date), factor.scores$scores) 
save(dt.fac.ec.daily, file = here('data', 'processed', 'fac-ec-daily.RDa'))
```

```{r Removing EC from factor analysis}
fit <- factanal(dt.pmc.daily %>% select(AS:ZN, OC), 8, rotation="varimax")
factor.loadings <- rbind(fit$loadings)
save(factor.loadings, file = here('output','table','factor-loadings.RDa'))
# Soil Metals Traffic Biomass Coal Salt Oil Steel
write.csv(factor.loadings,
          file = here('output','table', 'factor-loadings.csv'))

factor.scores <- factor.scores(dt.pmc.daily %>% select(AS:ZN, OC), fit)
dt.fac.daily <- cbind(dt.pmc.daily %>% select(Site.ID, Date), factor.scores$scores)
save(dt.fac.daily, file = here('data', 'processed', 'fac-daily.RDa'))
```

```{r Smoothing Factors & Caluculating 1-yr mvavg for each month}
dt.air <- dt.fac.daily %>% 
  pivot_longer(cols = Factor1:Factor8,
               names_to = "Parameter.Symbol",
               values_to = "Value") %>% 
  arrange(Site.ID, Parameter.Symbol, Date)

site.para <- dt.air %>% 
  distinct(Site.ID, Parameter.Symbol)

#using smoothed.yr function
smooth.out <- mapply(Smoothed.Year, 
                     site.para$Site.ID, site.para$Parameter.Symbol, 0.99, 350)
para.monthly <- data.frame(Site.ID=unlist(smooth.out[1,]),
                           Parameter.Symbol=unlist(smooth.out[2,]),
                           Date=unlist(smooth.out[3,]), 
                           para.1yr=unlist(smooth.out[4,]))

dt.fac.1yr <- para.monthly %>% 
  mutate(Year = floor(Date -0.01),
         Month = round((Date - Year)*12)) %>% 
  select(-Date) %>% 
  pivot_wider(names_sort = T,
              names_from = c(Parameter.Symbol),
              values_from = c(para.1yr)) %>% 
  arrange(Site.ID, Year, Month)

save(dt.fac.1yr, file = here('data', 'processed', 'fac-1yr.RDa'))
write.csv(dt.fac.1yr, file = here('data', 'processed', 'fac-1yr.csv'), row.names = F)
```

```{r Smoothing Factors & Caluculating 1-yr mvavg for each month with EC}
dt.air <- dt.fac.ec.daily %>% 
  pivot_longer(cols = Factor1:Factor8,
               names_to = "Parameter.Symbol",
               values_to = "Value") %>% 
  arrange(Site.ID, Parameter.Symbol, Date)

site.para <- dt.air %>% 
  distinct(Site.ID, Parameter.Symbol)

#using smoothed.yr function
smooth.out <- mapply(Smoothed.Year, 
                     site.para$Site.ID, site.para$Parameter.Symbol, 0.99, 350)
para.monthly <- data.frame(Site.ID=unlist(smooth.out[1,]),
                           Parameter.Symbol=unlist(smooth.out[2,]),
                           Date=unlist(smooth.out[3,]), 
                           para.1yr=unlist(smooth.out[4,]))

dt.fac.ec.1yr <- para.monthly %>% 
  mutate(Year = floor(Date -0.01),
         Month = round((Date - Year)*12)) %>% 
  select(-Date) %>% 
  pivot_wider(names_sort = T,
              names_from = c(Parameter.Symbol),
              values_from = c(para.1yr)) %>% 
  arrange(Site.ID, Year, Month)

save(dt.fac.ec.1yr, file = here('data', 'processed', 'fac-ec-1yr.RDa'))
write.csv(dt.fac.ec.1yr, file = here('data', 'processed', 'fac-ec-1yr.csv'), row.names = F)
```

```{r residuals of PM vs. Factors}
dt.pm.daily <- dt.pmc.daily %>% 
  select(Site.ID, Date, PM)

dt.fac.residual <- dt.fac.daily %>% 
  merge(dt.pm.daily) %>% 
  group_by(Site.ID) %>% 
  nest() %>% 
  mutate(PM_Factor1 = map(map(data, ~lm(PM ~ Factor1, data = .)), residuals),
         PM_Factor2 = map(map(data, ~lm(PM ~ Factor2, data = .)), residuals),
         PM_Factor3 = map(map(data, ~lm(PM ~ Factor3, data = .)), residuals),
         PM_Factor4 = map(map(data, ~lm(PM ~ Factor4, data = .)), residuals),
         PM_Factor5 = map(map(data, ~lm(PM ~ Factor5, data = .)), residuals),
         PM_Factor6 = map(map(data, ~lm(PM ~ Factor6, data = .)), residuals),
         PM_Factor7 = map(map(data, ~lm(PM ~ Factor7, data = .)), residuals),
         PM_Factor8 = map(map(data, ~lm(PM ~ Factor8, data = .)), residuals)
         ) %>% 
  unnest(c(data, PM_Factor1:PM_Factor8)) %>% 
  select(-(Factor1:Factor8), -PM)

save(dt.fac.residual, file = here('data', 'processed', 'fac-residual.RDa'))
```

```{r Smoothing Factors Residuals & Caluculating 1-yr mvavg for each month}
dt.air <- dt.fac.residual %>% 
  pivot_longer(cols = PM_Factor1:PM_Factor8,
               names_to = "Parameter.Symbol",
               values_to = "Value") %>% 
  arrange(Site.ID, Parameter.Symbol, Date)

site.para <- dt.air %>% 
  distinct(Site.ID, Parameter.Symbol)

#using smoothed.yr function
smooth.out <- mapply(Smoothed.Year, 
                     site.para$Site.ID, site.para$Parameter.Symbol, 0.99, 350)
para.monthly <- data.frame(Site.ID=unlist(smooth.out[1,]),
                           Parameter.Symbol=unlist(smooth.out[2,]),
                           Date=unlist(smooth.out[3,]), 
                           para.1yr=unlist(smooth.out[4,]))

dt.fac.residual.1yr <- para.monthly %>% 
  mutate(Year = floor(Date -0.01),
         Month = round((Date - Year)*12)) %>% 
  select(-Date) %>% 
  pivot_wider(names_sort = T,
              names_from = c(Parameter.Symbol),
              values_from = c(para.1yr)) %>% 
  arrange(Site.ID, Year, Month)

save(dt.fac.residual.1yr, file = here('data', 'processed', 'fac-residual-1yr.RDa'))

```

```{r}
Factor.to.Index <- tribble(
  ~Index, ~Parameter,
   "Soil", "Factor1",
   "Metals", "Factor2",
   "Traffic", "Factor3",
   "Biomass", "Factor4",
   "Coal", "Factor5",
   "Salt", "Factor6",
   "Oil", "Factor7",
   "Steel", "Factor8"
   ) %>% 
  mutate(Index = as.factor(Index),
         Parameter = as.factor(Parameter))
```

```{r Factor Score Mass Apportionment}
dt.pm.daily <- dt.pmc.daily %>% 
  select(Site.ID, Date, PM)

dt.fac.pm.daily <- dt.fac.daily %>% 
  merge(dt.pm.daily) %>% 
  rename("Soil" = Factor1,
         "Metals" = Factor2,
         "Traffic" = Factor3,
         "Biomass" = Factor4,
         "Coal" = Factor5,
         "Salt" = Factor6,
         "Oil" = Factor7,
         "Steel" = Factor8)

factor.mass <- lmer(data = dt.fac.pm.daily,
              PM ~ Soil + Metals + Traffic + Biomass + Coal + Salt + Oil + Steel+ (1|Site.ID))

tab_model(factor.mass, show.se = T, show.ci = F, show.aic = T,
          show.re.var = F, show.icc = T, show.obs = T, show.ngroups = T,
          title = "Factor Related PM Mass")
```

```{r Smoothing Source mass & Caluculating 1-yr mvavg for each month}
dt.air <- dt.fac.pm.daily %>%
  mutate(Soil.mass = so.coef(factor.mass, 'Soil') * Soil,
         Metals.mass = so.coef(factor.mass, 'Metals') * Metals,
         Traffic.mass = so.coef(factor.mass, 'Traffic') * Traffic,
         Biomass.mass = so.coef(factor.mass, 'Biomass') * Biomass,
         Coal.mass = so.coef(factor.mass, 'Coal') * Coal,
         Salt.mass = so.coef(factor.mass, 'Salt') * Salt,
         Oil.mass = so.coef(factor.mass, 'Oil') * Oil,
         Steel.mass = so.coef(factor.mass, 'Steel') * Steel) %>% 
  select(Site.ID, Date, Soil.mass:Steel.mass) %>% 
  pivot_longer(cols = c(Soil.mass:Steel.mass),
               names_to = "Parameter.Symbol",
               values_to = "Value") %>% 
  arrange(Site.ID, Parameter.Symbol, Date)

site.para <- dt.air %>% 
  distinct(Site.ID, Parameter.Symbol)

#using smoothed.yr function
smooth.out <- mapply(Smoothed.Year, 
                     site.para$Site.ID, site.para$Parameter.Symbol, 0.99, 350)
para.monthly <- data.frame(Site.ID=unlist(smooth.out[1,]),
                           Parameter.Symbol=unlist(smooth.out[2,]),
                           Date=unlist(smooth.out[3,]), 
                           para.1yr=unlist(smooth.out[4,]))

dt.mass.app.1yr.fac <- para.monthly %>% 
  mutate(Parameter.Symbol = sub("\\..*", "", Parameter.Symbol),
         Year = floor(Date -0.01),
         Month = round((Date - Year)*12)) %>% 
  select(-Date) %>% 
  pivot_wider(names_sort = T,
              names_from = c(Parameter.Symbol),
              values_from = c(para.1yr)) %>% 
  arrange(Site.ID, Year, Month)

save(dt.mass.app.1yr.fac, file = here('data', 'processed', 'mass-app-1yr-fac.RDa'))
write.csv(dt.mass.app.1yr.fac, file = here('data', 'processed', 'mass-app-1yr-fac.csv'), row.names = F)
```



```{r IQR test}
Soil  <-  so.coef(factor.mass, 'Soil') * 0.38
Metals <- so.coef(factor.mass, 'Metals') * 0.16
Traffic <- so.coef(factor.mass, 'Traffic') * 1.18
Biomass <- so.coef(factor.mass, 'Biomass') * 0.18
Coal <- so.coef(factor.mass, 'Coal') * 1.03
Salt <- so.coef(factor.mass, 'Salt') * 0.18
Oil <- so.coef(factor.mass, 'Oil') * 0.09
Steel <- so.coef(factor.mass, 'Steel') * 0.15

# Second way
dt.mass.app.1yr.fac %>% summarise_at(vars(Biomass:Traffic), ~IQR(.x))
```


```{r - Single Tracer Mass Regression Model Test}
# Factor order: Soil Metals Traffic Biomass Coal Salt Oil Steel
# Soil(Si), Metals(Pb), Traffic(Oc), Biomass(K),
# Coal(SO4), Salt(Cl), Oil(Ni), Steel(Fe)

### high load -- Comb1
high.load <- lmer(data = dt.pmc.daily,
              PM ~ SI + PB + OC + K + SO4 + CL + NI + FE + (1|Site.ID))
tab_model(high.load, show.se = T, show.ci = F, show.aic = T,
            show.re.var = F, show.icc = T, show.obs = T, show.ngroups = T,
          title = "Higher Load Tracers")

### high health impact ii - Comb2
high.health <- lmer(data = dt.pmc.daily,
              PM ~ SI + PB + NO3 + K + SO4 + CL + NI + MN + (1|Site.ID))
tab_model(high.health, show.se = T, show.ci = F, show.aic = T, digits = 2,
            show.re.var = F, show.icc = T, show.obs = T, show.ngroups = T,
          title = "Higher Health Impact Tracers - II")
# CL non sig

### Thurston
thurston <- lmer(data = dt.pmc.daily,
              PM ~ SI + ZN + NO3 + K + SO4 + CL + NI + FE + (1|Site.ID))
tab_model(thurston, show.se = T, show.ci = F, show.aic = T, digits = 2,
            show.re.var = F, show.icc = T, show.obs = T, show.ngroups = T,
          title = "Close to Thurston Tracers")
# Negative Ni
```


```{r - Single Tracer Mass Apportionment}
dt.sites <- dt.aqs.sites %>% 
  transmute(Site.ID,
            Latitude,
            Longitude,
            Location = ifelse(Location.Setting != "RURAL", "Urban", "Rural"),
            Region = ifelse(Region.IV == 1, "West",
                            ifelse(Region.IV == 2, "Midwest",
                                   ifelse(Region.IV == 3, "South", "Northeast"))))
            
Sources <- c("Soil", "Metals", "Traffic", "Biomass", "Coal", "Salt", "Oil", "Steel")
```


```{r - Single Tracer Mass Apportionment - Combination 1}
dt.mass.app.c1 <- dt.pmc.daily %>% 
  mutate(Soil = so.coef(high.load, 'SI') * SI,
         Metals = so.coef(high.load, 'PB') * PB,
         Traffic = so.coef(high.load, 'OC') * OC,
         Biomass = so.coef(high.load, 'K') * K,
         Coal = so.coef(high.load, 'SO4') * SO4,
         Salt = so.coef(high.load, 'CL') * CL,
         Oil = so.coef(high.load, 'NI') * NI,
         Steel = so.coef(high.load, 'FE') * FE) %>% 
  select(Site.ID, Date, PM, Sources) %>% 
  inner_join(dt.sites) %>% 
  pivot_longer(cols = c('PM', Sources),
               names_to = "Source",
               values_to = "Mass")

save(dt.mass.app.c1, file = here('data', 'processed', 'mass-apportioned-c1.RDa'))

mass.summary.us <- dt.mass.app.c1 %>% 
  group_by(Source) %>% 
  summarise(Mass.mean = round(mean(Mass),2),
            Mass.sd = round(sd(Mass),2)) %>% 
  mutate(Unit = "US")

mass.summary.region <- dt.mass.app.c1 %>% 
  group_by(Source, Region) %>% 
  summarise(Mass.mean = round(mean(Mass),2),
            Mass.sd = round(sd(Mass),2)) %>% 
  rename(Unit = Region)

mass.summary.locset <- dt.mass.app.c1 %>% 
  group_by(Source, Location) %>% 
  summarise(Mass.mean = round(mean(Mass),2),
            Mass.sd = round(sd(Mass),2)) %>% 
rename(Unit = Location)

mass.summary.c1 <- mass.summary.us %>% 
  add_row(mass.summary.region) %>% 
  add_row(mass.summary.locset)

write.csv(mass.summary.c1,
          file = here('output','table', 'mass-app-summary-c1.csv'))

dt.mass.map.c1 <- dt.mass.app.c1 %>% 
  group_by(Site.ID, Source) %>% 
  summarise(Mass = mean(Mass)) %>% 
  pivot_wider(names_from = "Source",
              values_from = "Mass") %>% 
  inner_join(dt.sites)

save(dt.mass.map.c1, file = here('data', 'processed', 'mass-map-c1.RDa'))
write.csv(dt.mass.map.c1, file = here('output','table', 'mass-map-c1.csv'), row.names = F)
```

```{r Smoothing Data & Caluculating 1-yr mvavg for each month - Combination 1}
dt.air <- dt.mass.app.c1 %>% 
  transmute(Site.ID,
            Parameter.Symbol = Source,
            Date,
            Value = Mass) %>% 
  arrange(Site.ID, Parameter.Symbol, Date)

site.para <- dt.air %>% 
  distinct(Site.ID, Parameter.Symbol)

#using smoothed.yr function
smooth.out <- mapply(Smoothed.Year, 
                     site.para$Site.ID, site.para$Parameter.Symbol, 0.99, 350)
para.monthly <- data.frame(Site.ID=unlist(smooth.out[1,]),
                           Parameter.Symbol=unlist(smooth.out[2,]),
                           Date=unlist(smooth.out[3,]), 
                           para.1yr=unlist(smooth.out[4,]))

dt.mass.app.1yr.c1 <- para.monthly %>% 
  mutate(Year = floor(Date -0.01),
         Month = round((Date - Year)*12)) %>% 
  select(-Date) %>% 
  pivot_wider(names_sort = T,
              names_from = c(Parameter.Symbol),
              values_from = c(para.1yr)) %>% 
  arrange(Site.ID, Year, Month)

save(dt.mass.app.1yr.c1, file = here('data', 'processed', 'mass-app-1yr-c1.RDa'))
write.csv(dt.mass.app.1yr.c1, file = here('data', 'processed', 'mass-app-1yr-c1.csv'), row.names = F)
```

```{r - Single Tracer Mass Apportionment - Combination 2 - Preferred}
dt.mass.app.c2 <- dt.pmc.daily %>% 
  mutate(Soil = so.coef(high.health, 'SI') * SI,
         Metals = so.coef(high.health, 'PB') * PB,
         Traffic = so.coef(high.health, 'NO3') * NO3,
         Biomass = so.coef(high.health, 'K') * K,
         Coal = so.coef(high.health, 'SO4') * SO4,
         Salt = so.coef(high.health, 'CL') * CL,
         Oil = so.coef(high.health, 'NI') * NI,
         Steel = so.coef(high.health, 'MN') * MN) %>% 
  select(Site.ID, Date, PM, Sources) %>% 
  inner_join(dt.sites) %>% 
  pivot_longer(cols = c('PM', Sources),
               names_to = "Source",
               values_to = "Mass")

save(dt.mass.app.c2, file = here('data', 'processed', 'mass-apportioned-c2.RDa'))

mass.summary.us <- dt.mass.app.c2 %>% 
  group_by(Source) %>% 
  summarise(Mass.mean = round(mean(Mass),2),
            Mass.sd = round(sd(Mass),2)) %>% 
  mutate(Unit = "US")

mass.summary.region <- dt.mass.app.c2 %>% 
  group_by(Source, Region) %>% 
  summarise(Mass.mean = round(mean(Mass),2),
            Mass.sd = round(sd(Mass),2)) %>% 
  rename(Unit = Region)

mass.summary.locset <- dt.mass.app.c2 %>% 
  group_by(Source, Location) %>% 
  summarise(Mass.mean = round(mean(Mass),2),
            Mass.sd = round(sd(Mass),2)) %>% 
rename(Unit = Location)

mass.summary.c2 <- mass.summary.us %>% 
  add_row(mass.summary.region) %>% 
  add_row(mass.summary.locset)

write.csv(mass.summary.c2,
          file = here('output','table', 'mass-app-summary-c2.csv'))

dt.mass.map.c2 <- dt.mass.app.c2 %>% 
  group_by(Site.ID, Source) %>% 
  summarise(Mass = mean(Mass)) %>% 
  pivot_wider(names_from = "Source",
              values_from = "Mass") %>% 
  inner_join(dt.sites)

save(dt.mass.map.c2, file = here('data', 'processed', 'mass-map-c2.RDa'))
write.csv(dt.mass.map.c2, file = here('output','table', 'mass-map-c2.csv'), row.names = F)
```

```{r Smoothing Data & Caluculating 1-yr mvavg for each month - Combination 2}
dt.air <- dt.mass.app.c2 %>% 
  transmute(Site.ID,
            Parameter.Symbol = Source,
            Date,
            Value = Mass) %>% 
  arrange(Site.ID, Parameter.Symbol, Date)

site.para <- dt.air %>% 
  distinct(Site.ID, Parameter.Symbol)

#using smoothed.yr function
smooth.out <- mapply(Smoothed.Year, 
                     site.para$Site.ID, site.para$Parameter.Symbol, 0.99, 350)
para.monthly <- data.frame(Site.ID=unlist(smooth.out[1,]),
                           Parameter.Symbol=unlist(smooth.out[2,]),
                           Date=unlist(smooth.out[3,]), 
                           para.1yr=unlist(smooth.out[4,]))

dt.mass.app.1yr.c2 <- para.monthly %>% 
  mutate(Year = floor(Date -0.01),
         Month = round((Date - Year)*12)) %>% 
  select(-Date) %>% 
  pivot_wider(names_sort = T,
              names_from = c(Parameter.Symbol),
              values_from = c(para.1yr)) %>% 
  arrange(Site.ID, Year, Month)

save(dt.mass.app.1yr.c2, file = here('data', 'processed', 'mass-app-1yr-c2.RDa'))
write.csv(dt.mass.app.1yr.c2, file = here('data', 'processed', 'mass-app-1yr-c2.csv'), row.names = F)
```














