---
title: "Air Quality and CMS Data"
author: "Fatemeh Kazemi"
date: "1/18/2021"
output: html_document
---

### This program:
  (1) Merges CMS(ndi) data with pmc and ses data
  
### Note:
  1. In data merged with CMS, bufferzone is 12-mile unless specified
  2. Exposure window is one year unless specified
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages}
library(tidyverse)
library(here)
```

```{r load data}
dirUSSpatial <- 'C:\\Users\\fkazem01\\Box\\Projects\\USA Spatial\\data\\processed\\'
load(paste0(dirUSSpatial,'ses-site-bz12.RDa'))
load(paste0(dirUSSpatial,'ses-site-bz6.RDa'))
load(paste0(dirUSSpatial,'ses-site-bz24.RDa'))
load(paste0(dirUSSpatial,'brfss-site.RDa'))
load(here('data','processed','master-ndi-pmc.RDa'))
load(here('data','processed','master-ndi-pmc-race.RDa'))
load(here('data','processed','pmc-site-ndi.RDa'))
load(here('data','processed','pmc-1yr.RDa'))
load(here('data','processed','fac-1yr.RDa'))
load(here('data','processed','fac-ex-ec-1yr.RDa'))
load(here('data','processed','pmc-residual-1yr.RDa'))
load(here('data','processed','fac-ex-ec-residual-1yr.RDa'))
load(here('data','processed','pmc-sub-5yr.RDa'))
load(here('data','processed','pmc-sub-4yr-5yr.RDa'))
load(here('data','processed','pmc-sub-3yr-5yr.RDa'))
load(here('data','processed','pmc-sub-2yr-5yr.RDa'))
load(here('data','processed','pmc-sub-1yr-5yr.RDa'))
```

```{r Import and save CMS(/ndi) data}
# bz = 12
dt.master.ndi.pmc <- read.csv(
  here('data', 'processed','master_ndi_pmc.csv')) %>% 
  rename(Site.ID = Site_ID,
         Year = year,
         Month = MONTH,
         age = ENROLLEE_AGE)
save(dt.master.ndi.pmc, 
     file = here('data', 'processed', 'master-ndi-pmc.RDa'))

# bz =12 - race
dt.master.ndi.pmc.race <- read.csv(
  here('data', 'processed','master_ndi_pmc_race.csv')) %>%
  rename(Site.ID = Site_ID,
         Year = year,
         Month = MONTH,
         age = ENROLLEE_AGE)
save(dt.master.ndi.pmc.race, 
     file = here('data', 'processed', 'master-ndi-pmc-race.RDa'))

# bz = 6
dt.master.ndi.pmc.bz6 <- read.csv(
  here('data', 'processed','master_ndi_pmc_bz6.csv')) %>% 
  rename(Site.ID = Site_ID,
         Year = year,
         Month = MONTH,
         age = ENROLLEE_AGE)
save(dt.master.ndi.pmc.bz6, 
     file = here('data', 'processed', 'master-ndi-pmc-bz6.RDa'))

# bz = 12 of sites of bz =6
dt.master.ndi.pmc.bz12 <- read.csv(
  here('data', 'processed','master_ndi_pmc_bz12.csv')) %>% 
  rename(Site.ID = Site_ID,
         Year = year,
         Month = MONTH,
         age = ENROLLEE_AGE)
save(dt.master.ndi.pmc.bz12, 
     file = here('data', 'processed', 'master-ndi-pmc-bz12.RDa'))

# bz = 24 of sites of bz =6
dt.master.ndi.pmc.bz24 <- read.csv(
  here('data', 'processed','master_ndi_pmc_bz24.csv')) %>% 
  rename(Site.ID = Site_ID,
         Year = year,
         Month = MONTH,
         age = ENROLLEE_AGE)
save(dt.master.ndi.pmc.bz24, 
     file = here('data', 'processed', 'master-ndi-pmc-bz24.RDa'))
```

```{r PMC}
dt.pmc <- dt.pmc.1yr %>% 
  rename_at(vars(AS:ZN), ~paste("Yr", .x, sep = "_"))

dt.ses <- dt.ses.site.bz12 %>% 
  mutate(ses = SES.Zip.Norm) %>% 
  select(Site.ID, Year, ses)

dt.ndi.pmc <- dt.master.ndi.pmc %>% 
  mutate(StrID = paste(age, sex, race)) %>% 
  select(Site.ID, Year, Month, StrID, no_enrollee:no_death_kidn) %>%  
  inner_join(dt.pmc) %>% 
  inner_join(dt.ses) %>% 
  rename(SiteID = Site.ID)

write.csv(dt.ndi.pmc, 
          file = here('data', 'processed', 'ndi-pmc.csv'),
          row.names = F)
```

```{r Factors}
dt.ses <- dt.ses.site.bz12 %>% 
  mutate(ses = SES.Zip.Norm) %>% 
  select(Site.ID, Year, ses)

dt.ndi.fac <- dt.master.ndi.pmc %>% 
  mutate(StrID = paste(age, sex, race)) %>% 
  select(Site.ID, Year, Month, StrID, no_enrollee:no_death_kidn) %>%  
  inner_join(dt.fac.1yr) %>% 
  inner_join(dt.ses) %>% 
  rename(SiteID = Site.ID)

write.csv(dt.ndi.fac, 
          file = here('data', 'processed', 'ndi-fac.csv'),
          row.names = F)
```

```{r Factors Excluding EC}
dt.ses <- dt.ses.site.bz12 %>% 
  mutate(ses = SES.Zip.Norm) %>% 
  select(Site.ID, Year, ses)

dt.ndi.fac.ex.ec <- dt.master.ndi.pmc %>% 
  mutate(StrID = paste(age, sex, race)) %>% 
  select(Site.ID, Year, Month, StrID, no_enrollee:no_death_kidn) %>%  
  inner_join(dt.fac.ex.ec.1yr) %>% 
  inner_join(dt.ses) %>% 
  rename(SiteID = Site.ID)

write.csv(dt.ndi.fac.ex.ec, 
          file = here('data', 'processed', 'ndi-fac-ex-ec.csv'),
          row.names = F)
```

```{r Carbons}
dt.carbon <- dt.pmc.1yr %>% 
  select(Site.ID, Year, Month, EC, OC) %>% 
  rename_at(vars(EC, OC), ~paste("Yr", .x, sep = "_"))

dt.site <- dt.pmc.site.ndi %>% 
  filter(!Method == "EC.TOT-OC.TOR") %>% 
  select(Site.ID, Method)

dt.ses <- dt.ses.site.bz12 %>% 
  mutate(ses = SES.Zip.Norm) %>% 
  select(Site.ID, Year, ses)

dt.ndi.carbon <- dt.master.ndi.pmc %>% 
  mutate(StrID = paste(age, sex, race)) %>% 
  select(Site.ID, Year, Month, StrID, no_enrollee:no_death_lungc,
         -no_death_uri, -no_death_ards) %>%  
  inner_join(dt.carbon) %>% 
  inner_join(dt.site) %>% 
  inner_join(dt.ses) %>% 
  rename(SiteID = Site.ID) %>% 
  select(-Method)

write.csv(dt.ndi.carbon, 
          file = here('data', 'processed', 'ndi-carbon.csv'), 
          row.names = F)

dt.ndi.carbon.tot <- dt.master.ndi.pmc %>% 
  mutate(StrID = paste(age, sex, race)) %>% 
  select(Site.ID, Year, Month, StrID, no_enrollee:no_death_lungc,
         -no_death_uri, -no_death_ards) %>%  
  inner_join(dt.carbon) %>% 
  inner_join(dt.site) %>% 
  inner_join(dt.ses) %>% 
  rename(SiteID = Site.ID) %>% 
  filter(Method == "TOT") %>% 
  select(-Method)

write.csv(dt.ndi.carbon.tot, 
          file = here('data', 'processed', 'ndi-carbon-tot.csv'), 
          row.names = F)

dt.ndi.carbon.tor <- dt.master.ndi.pmc %>% 
  mutate(StrID = paste(age, sex, race)) %>% 
  select(Site.ID, Year, Month, StrID, no_enrollee:no_death_lungc,
         -no_death_uri, -no_death_ards) %>%  
  inner_join(dt.carbon) %>% 
  inner_join(dt.site) %>% 
  inner_join(dt.ses) %>% 
  rename(SiteID = Site.ID) %>% 
  filter(Method == "TOR") %>% 
  select(-Method)

write.csv(dt.ndi.carbon.tor, 
          file = here('data', 'processed', 'ndi-carbon-tor.csv'),
          row.names = F)
``` 

```{r PMC Residual}
cmp.sub <- c("PM_AS","PM_CA","PM_CL","PM_NA","PM_NI","PM_NO3",
            "PM_OC","PM_PB","PM_SI","PM_SO4","PM_V","PM_ZN")

dt.pmc <- dt.pmc.residual.1yr %>% 
  select(Site.ID, Year, Month, cmp.sub)

dt.ses <- dt.ses.site.bz12 %>% 
  mutate(ses = SES.Zip.Norm) %>% 
  select(Site.ID, Year, ses)

dt.ndi.pmc.residual <- dt.master.ndi.pmc %>% 
  mutate(StrID = paste(age, sex, race)) %>% 
  select(Site.ID, Year, Month, StrID, no_enrollee:no_death_lungc,
         -no_death_uri, -no_death_ards) %>%  
  inner_join(dt.pmc) %>% 
  inner_join(dt.ses) %>% 
  rename(SiteID = Site.ID)

write.csv(dt.ndi.pmc.residual, 
          file = here('data', 'processed', 'ndi-pmc-residual.csv'), 
          row.names = F)
```

```{r Factors Excluding EC Residual}
dt.ses <- dt.ses.site.bz12 %>% 
  mutate(ses = SES.Zip.Norm) %>% 
  select(Site.ID, Year, ses)

dt.ndi.fac.ex.ec.residual <- dt.master.ndi.pmc %>% 
  mutate(StrID = paste(age, sex, race)) %>% 
  select(Site.ID, Year, Month, StrID, no_enrollee:no_enrollee:no_death_lungc,
         -no_death_uri, -no_death_ards) %>%  
  inner_join(dt.fac.ex.ec.residual.1yr) %>% 
  inner_join(dt.ses) %>% 
  rename(SiteID = Site.ID)

write.csv(dt.ndi.fac.ex.ec.residual, 
          file = here('data', 'processed', 'ndi-fac-ex-ec-residual.csv'),
          row.names = F)
```

```{r PMC race}
cmp.sub <- c("AS", "CA", "CL", "NA", "NI", "NO3", "OC", 
             "PB", "PM", "SI", "SO4", "V", "ZN")

dt.pmc <- dt.pmc.1yr %>% 
  select(Site.ID, Year, Month, cmp.sub)

dt.ses <- dt.ses.site.bz12 %>% 
  mutate(ses = SES.Zip.Norm) %>% 
  select(Site.ID, Year, ses)

### Race Asian
dt.raceA <- dt.master.ndi.pmc.race %>%
  mutate(race = ifelse(!race == "A", "O", "A")) %>% 
  select(Site.ID:no_death_lungc,
         -no_death_uri, -no_death_ards)

dt.raceA <- aggregate(. ~ Site.ID + Year + Month + age + sex + race, dt.raceA, sum) %>%
  arrange(Site.ID, Year, Month, age, sex, race)

dt.ndi.pmc.raceA <- dt.raceA %>% 
  inner_join(dt.pmc) %>% 
  inner_join(dt.ses) %>% 
  mutate(rA = ifelse(race == "A", 0,1),
         StrID = paste(age, sex, race)) %>% 
  select(-age, -sex, -race) 
  
for (cmp in cmp.sub){
    dt.ndi.pmc.raceA[ ,paste0("rA_",cmp)] <- 
      dt.ndi.pmc.raceA[ ,cmp] * dt.ndi.pmc.raceA$rA
}

dt.ndi.pmc.raceA <- dt.ndi.pmc.raceA %>% 
  rename_at(vars(AS:ZN), ~paste("Yr", .x, sep = "_")) %>% 
  rename(SiteID = Site.ID) %>% 
  select(SiteID, Year, Month, StrID, rA, everything())

write.csv(dt.ndi.pmc.raceA, 
          file = here('data', 'processed', 'ndi-pmc-raceA.csv'),
          row.names = F)

### Race Black
dt.raceB <- dt.master.ndi.pmc.race %>%
  mutate(race = ifelse(!race == "B", "O", "B")) %>% 
  select(Site.ID:no_death_lungc,
         -no_death_uri, -no_death_ards)

dt.raceB <- 
  aggregate(. ~ Site.ID + Year + Month + age + sex + race, dt.raceB, sum) %>%
  arrange(Site.ID, Year, Month, age, sex, race)

dt.ndi.pmc.raceB <- dt.raceB %>% 
  inner_join(dt.pmc) %>% 
  inner_join(dt.ses) %>% 
  mutate(rB = ifelse(race == "B", 0,1),
         StrID = paste(age, sex, race)) %>% 
  select(-age, -sex, -race) 
  
for (cmp in cmp.sub){
    dt.ndi.pmc.raceB[ ,paste0("rB_",cmp)] <- 
      dt.ndi.pmc.raceB[ ,cmp] * dt.ndi.pmc.raceB$rB
}

dt.ndi.pmc.raceB <- dt.ndi.pmc.raceB %>% 
  rename_at(vars(AS:ZN), ~paste("Yr", .x, sep = "_")) %>% 
  rename(SiteID = Site.ID) %>% 
  select(SiteID, Year, Month, StrID, rB, everything())

write.csv(dt.ndi.pmc.raceB, 
          file = here('data', 'processed', 'ndi-pmc-raceB.csv'),
          row.names = F)

### Race Hispanic
dt.raceH <- dt.master.ndi.pmc.race %>%
  mutate(race = ifelse(!race == "H", "O", "H")) %>% 
  select(Site.ID:no_death_lungc,
         -no_death_uri, -no_death_ards)

dt.raceH <- 
  aggregate(. ~ Site.ID + Year + Month + age + sex + race, dt.raceH, sum) %>%
  arrange(Site.ID, Year, Month, age, sex, race)

dt.ndi.pmc.raceH <- dt.raceH %>% 
  inner_join(dt.pmc) %>% 
  inner_join(dt.ses) %>% 
  mutate(rH = ifelse(race == "H", 0,1),
         StrID = paste(age, sex, race)) %>% 
  select(-age, -sex, -race) 
  
for (cmp in cmp.sub){
    dt.ndi.pmc.raceH[ ,paste0("rH_",cmp)] <- 
      dt.ndi.pmc.raceH[ ,cmp] * dt.ndi.pmc.raceH$rH
}

dt.ndi.pmc.raceH <- dt.ndi.pmc.raceH %>% 
  rename_at(vars(AS:ZN), ~paste("Yr", .x, sep = "_")) %>% 
  rename(SiteID = Site.ID) %>% 
  select(SiteID, Year, Month, StrID, rH, everything())

write.csv(dt.ndi.pmc.raceH, 
          file = here('data', 'processed', 'ndi-pmc-raceH.csv'),
          row.names = F)


### Race White
dt.raceW <- dt.master.ndi.pmc.race %>%
  mutate(race = ifelse(!race == "W", "O", "W")) %>% 
  select(Site.ID:no_death_lungc,
         -no_death_uri, -no_death_ards)

dt.raceW <- 
  aggregate(. ~ Site.ID + Year + Month + age + sex + race, dt.raceW, sum) %>%
  arrange(Site.ID, Year, Month, age, sex, race)

dt.ndi.pmc.raceW <- dt.raceW %>% 
  inner_join(dt.pmc) %>% 
  inner_join(dt.ses) %>% 
  mutate(rW = ifelse(race == "W", 0,1),
         StrID = paste(age, sex, race)) %>% 
  select(-age, -sex, -race) 
  
for (cmp in cmp.sub){
    dt.ndi.pmc.raceW[ ,paste0("rW_",cmp)] <- 
      dt.ndi.pmc.raceW[ ,cmp] * dt.ndi.pmc.raceW$rW
}

dt.ndi.pmc.raceW <- dt.ndi.pmc.raceW %>% 
  rename_at(vars(AS:ZN), ~paste("Yr", .x, sep = "_")) %>% 
  rename(SiteID = Site.ID) %>% 
  select(SiteID, Year, Month, StrID, rW, everything())

write.csv(dt.ndi.pmc.raceW, 
          file = here('data', 'processed', 'ndi-pmc-raceW.csv'),
          row.names = F)
```

```{r Factor race}
fac <- c("Factor1","Factor2","Factor3","Factor4",
         "Factor5","Factor6","Factor7","Factor8")

dt.ses <- dt.ses.site.bz12 %>% 
  mutate(ses = SES.Zip.Norm) %>% 
  select(Site.ID, Year, ses)

### Race Asian
dt.raceA <- dt.master.ndi.pmc.race %>%
  mutate(race = ifelse(!race == "A", "O", "A")) %>% 
  select(Site.ID:no_death_lungc,
         -no_death_uri, -no_death_ards)

dt.raceA <- 
  aggregate(. ~ Site.ID + Year + Month + age + sex + race, dt.raceA, sum) %>%
  arrange(Site.ID, Year, Month, age, sex, race)

dt.ndi.fac.raceA <- dt.raceA %>% 
  inner_join(dt.fac.1yr) %>% 
  inner_join(dt.ses) %>% 
  mutate(rA = ifelse(race == "A", 0,1),
         StrID = paste(age, sex, race)) %>% 
  select(-age, -sex, -race) 
  
for (cmp in fac){
    dt.ndi.fac.raceA[ ,paste0("rA_",cmp)] <- 
      dt.ndi.fac.raceA[ ,cmp] * dt.ndi.fac.raceA$rA
}

dt.ndi.fac.raceA <- dt.ndi.fac.raceA %>% 
  rename(SiteID = Site.ID) %>% 
  select(SiteID, Year, Month, StrID, rA, everything())

write.csv(dt.ndi.fac.raceA, 
          file = here('data', 'processed', 'ndi-fac-raceA.csv'),
          row.names = F)

### Race Black
dt.raceB <- dt.master.ndi.fac.race %>%
  mutate(race = ifelse(!race == "B", "O", "B")) %>% 
  select(Site.ID:no_death_lungc,
         -no_death_uri, -no_death_ards)

dt.raceB <- 
  aggregate(. ~ Site.ID + Year + Month + age + sex + race, dt.raceB, sum) %>%
  arrange(Site.ID, Year, Month, age, sex, race)

dt.ndi.fac.raceB <- dt.raceB %>% 
  inner_join(dt.fac.1yr) %>% 
  inner_join(dt.ses) %>% 
  mutate(rB = ifelse(race == "B", 0,1),
         StrID = paste(age, sex, race)) %>% 
  select(-age, -sex, -race) 
  
for (cmp in fac){
    dt.ndi.fac.raceB[ ,paste0("rB_",cmp)] <- 
      dt.ndi.fac.raceB[ ,cmp] * dt.ndi.fac.raceB$rB
}

dt.ndi.fac.raceB <- dt.ndi.fac.raceB %>% 
  rename(SiteID = Site.ID) %>% 
  select(SiteID, Year, Month, StrID, rB, everything())

write.csv(dt.ndi.fac.raceB, 
          file = here('data', 'processed', 'ndi-fac-raceB.csv'),
          row.names = F)

### Race Hispanic
dt.raceH <- dt.master.ndi.fac.race %>%
  mutate(race = ifelse(!race == "H", "O", "H")) %>% 
  select(Site.ID:no_death_lungc,
         -no_death_uri, -no_death_ards)

dt.raceH <- 
  aggregate(. ~ Site.ID + Year + Month + age + sex + race, dt.raceH, sum) %>%
  arrange(Site.ID, Year, Month, age, sex, race)

dt.ndi.fac.raceH <- dt.raceH %>% 
  inner_join(dt.fac.1yr) %>% 
  inner_join(dt.ses) %>% 
  mutate(rH = ifelse(race == "H", 0,1),
         StrID = paste(age, sex, race)) %>% 
  select(-age, -sex, -race) 
  
for (cmp in fac){
    dt.ndi.fac.raceH[ ,paste0("rH_",cmp)] <- 
      dt.ndi.fac.raceH[ ,cmp] * dt.ndi.fac.raceH$rH
}

dt.ndi.fac.raceH <- dt.ndi.fac.raceH %>% 
  rename(SiteID = Site.ID) %>% 
  select(SiteID, Year, Month, StrID, rH, everything())

write.csv(dt.ndi.fac.raceH, 
          file = here('data', 'processed', 'ndi-fac-raceH.csv'),
          row.names = F)


### Race White
dt.raceW <- dt.master.ndi.fac.race %>%
  mutate(race = ifelse(!race == "W", "O", "W")) %>% 
  select(Site.ID:no_death_lungc,
         -no_death_uri, -no_death_ards)

dt.raceW <- 
  aggregate(. ~ Site.ID + Year + Month + age + sex + race, dt.raceW, sum) %>%
  arrange(Site.ID, Year, Month, age, sex, race)

dt.ndi.fac.raceW <- dt.raceW %>% 
  inner_join(dt.fac.1yr) %>% 
  inner_join(dt.ses) %>% 
  mutate(rW = ifelse(race == "W", 0,1),
         StrID = paste(age, sex, race)) %>% 
  select(-age, -sex, -race) 
  
for (cmp in fac){
    dt.ndi.fac.raceW[ ,paste0("rW_",cmp)] <- 
      dt.ndi.fac.raceW[ ,cmp] * dt.ndi.fac.raceW$rW
}

dt.ndi.fac.raceW <- dt.ndi.fac.raceW %>% 
  rename(SiteID = Site.ID) %>% 
  select(SiteID, Year, Month, StrID, rW, everything())

write.csv(dt.ndi.fac.raceW, 
          file = here('data', 'processed', 'ndi-fac-raceW.csv'),
          row.names = F)
```

```{r PMC urbanicity}
cmp.sub <- c("AS", "CA", "CL", "NA", "NI", "NO3", "OC", 
             "PB", "PM", "SI", "SO4", "V", "ZN")

dt.pmc <- dt.pmc.1yr %>% 
  select(Site.ID, Year, Month, cmp.sub)

dt.ses <- dt.ses.site.bz12 %>% 
  mutate(ses = SES.Zip.Norm) %>% 
  select(Site.ID, Year, ses)

dt.site <- dt.pmc.site.ndi %>% 
  select(Site.ID, Location.Setting)

### Urban and Suburban
dt.ndi.pmc.urban <- dt.master.ndi.pmc %>% 
  select(Site.ID:no_death_lungc,
         -no_death_uri, -no_death_ards) %>% 
  inner_join(dt.pmc) %>% 
  inner_join(dt.ses) %>% 
  inner_join(dt.site) %>% 
  mutate(urb = ifelse(!Location.Setting == "RURAL", 0,1),
         StrID = paste(age, sex, race)) %>% 
  select(-age, -sex, -race, -Location.Setting) 
  
for (cmp in cmp.sub){
    dt.ndi.pmc.urban[ ,paste0("urb_",cmp)] <- 
      dt.ndi.pmc.urban[ ,cmp] * dt.ndi.pmc.urban$urb
}

dt.ndi.pmc.urban <- dt.ndi.pmc.urban %>% 
  rename_at(vars(AS:ZN), ~paste("Yr", .x, sep = "_")) %>% 
  rename(SiteID = Site.ID) %>% 
  select(SiteID, Year, Month, StrID, urb, everything())

write.csv(dt.ndi.pmc.urban, 
          file = here('data', 'processed', 'ndi-pmc-urban.csv'),
          row.names = F)


### Rural
dt.ndi.pmc.rural <- dt.master.ndi.pmc %>% 
  select(Site.ID:no_death_lungc,
         -no_death_uri, -no_death_ards) %>% 
  inner_join(dt.pmc) %>% 
  inner_join(dt.ses) %>% 
  inner_join(dt.site) %>% 
  mutate(rur = ifelse(Location.Setting == "RURAL", 0,1),
         StrID = paste(age, sex, race)) %>% 
  select(-age, -sex, -race, -Location.Setting) 
  
for (cmp in cmp.sub){
    dt.ndi.pmc.rural[ ,paste0("rur_",cmp)] <- 
      dt.ndi.pmc.rural[ ,cmp] * dt.ndi.pmc.rural$rur
}

dt.ndi.pmc.rural <- dt.ndi.pmc.rural %>% 
  rename_at(vars(AS:ZN), ~paste("Yr", .x, sep = "_")) %>% 
  rename(SiteID = Site.ID) %>% 
  select(SiteID, Year, Month, StrID, rur, everything())

write.csv(dt.ndi.pmc.rural, 
          file = here('data', 'processed', 'ndi-pmc-rural.csv'),
          row.names = F)
```

```{r r PMC urban SES Categories}
dt.ses <- dt.ses.site.bz12 %>% 
  mutate(ses = SES.Zip.Norm) %>% 
  select(Site.ID, Year, ses)

dt.site.urban <- dt.pmc.site.ndi %>% 
  filter(!Location.Setting == "RURAL") %>% 
  select(Site.ID)

dt.site.urban.ses.cat <- dt.site.urban %>% 
  inner_join(dt.ses)

qtl <- dt.site.urban.ses.cat %>% 
  summarise(qtl = quantile(ses, c(0.33, 0.66)))

dt.site.urban.ses.cat <- dt.site.urban.ses.cat %>% 
  mutate(ses.cat = ifelse(ses < qtl[1,], "Low",
                          ifelse(ses >qtl[1,] & ses < qtl[2,], "Mid", "High")))

cmp.sub <- c("AS", "CA", "CL", "NA", "NI", "NO3", "OC", 
             "PB", "PM", "SI", "SO4", "V", "ZN")

dt.pmc <- dt.pmc.1yr %>% 
  select(Site.ID, Year, Month, cmp.sub)

### Low Income
dt.ndi.pmc.urban.ses <- dt.master.ndi.pmc %>% 
  select(Site.ID:no_death_lungc,
         -no_death_uri, -no_death_ards) %>% 
  inner_join(dt.pmc) %>% 
  inner_join(dt.site.urban.ses.cat) %>%  
  mutate(sesL = ifelse(ses.cat == "Low", 0,1),
         StrID = paste(age, sex, race)) %>% 
  select(-age, -sex, -race, -ses.cat) 
  
for (cmp in cmp.sub){
    dt.ndi.pmc.urban.ses[ ,paste0("sesL_",cmp)] <- 
      dt.ndi.pmc.urban.ses[ ,cmp] * dt.ndi.pmc.urban.ses$sesL
}

dt.ndi.pmc.urban.sesL <- dt.ndi.pmc.urban.ses %>% 
  rename_at(vars(AS:ZN), ~paste("Yr", .x, sep = "_")) %>% 
  rename(SiteID = Site.ID) %>% 
  select(SiteID, Year, Month, StrID, sesL, everything())

write.csv(dt.ndi.pmc.urban.sesL, 
          file = here('data', 'processed', 'ndi-pmc-urban-sesL.csv'),
          row.names = F)

### Middle Income
dt.ndi.pmc.urban.ses <- dt.master.ndi.pmc %>% 
  select(Site.ID:no_death_lungc,
         -no_death_uri, -no_death_ards) %>% 
  inner_join(dt.pmc) %>% 
  inner_join(dt.site.urban.ses.cat) %>%  
  mutate(sesM = ifelse(ses.cat == "Mid", 0,1),
         StrID = paste(age, sex, race)) %>% 
  select(-age, -sex, -race, -ses.cat) 
  
for (cmp in cmp.sub){
    dt.ndi.pmc.urban.ses[ ,paste0("sesM_",cmp)] <- 
      dt.ndi.pmc.urban.ses[ ,cmp] * dt.ndi.pmc.urban.ses$sesM
}

dt.ndi.pmc.urban.sesM <- dt.ndi.pmc.urban.ses %>% 
  rename_at(vars(AS:ZN), ~paste("Yr", .x, sep = "_")) %>% 
  rename(SiteID = Site.ID) %>% 
  select(SiteID, Year, Month, StrID, sesM, everything())

write.csv(dt.ndi.pmc.urban.sesM, 
          file = here('data', 'processed', 'ndi-pmc-urban-sesM.csv'),
          row.names = F)

### High Income
dt.ndi.pmc.urban.ses <- dt.master.ndi.pmc %>% 
  select(Site.ID:no_death_lungc,
         -no_death_uri, -no_death_ards) %>% 
  inner_join(dt.pmc) %>% 
  inner_join(dt.site.urban.ses.cat) %>%  
  mutate(sesH = ifelse(ses.cat == "Mid", 0,1),
         StrID = paste(age, sex, race)) %>% 
  select(-age, -sex, -race, -ses.cat) 
  
for (cmp in cmp.sub){
    dt.ndi.pmc.urban.ses[ ,paste0("sesH_",cmp)] <- 
      dt.ndi.pmc.urban.ses[ ,cmp] * dt.ndi.pmc.urban.ses$sesH
}

dt.ndi.pmc.urban.sesH <- dt.ndi.pmc.urban.ses %>% 
  rename_at(vars(AS:ZN), ~paste("Yr", .x, sep = "_")) %>% 
  rename(SiteID = Site.ID) %>% 
  select(SiteID, Year, Month, StrID, sesH, everything())

write.csv(dt.ndi.pmc.urban.sesH, 
          file = here('data', 'processed', 'ndi-pmc-urban-sesH.csv'),
          row.names = F)
```

```{r PMC Region}
cmp.sub <- c("AS", "CA", "CL", "NA", "NI", "NO3", "OC", 
             "PB", "PM", "SI", "SO4", "V", "ZN")

dt.pmc <- dt.pmc.1yr %>% 
  select(Site.ID, Year, Month, cmp.sub)

dt.ses <- dt.ses.site.bz12 %>% 
  mutate(ses = SES.Zip.Norm) %>% 
  select(Site.ID, Year, ses)

dt.site <- dt.pmc.site.ndi %>% 
  select(Site.ID, Region.IV)

### West = 1
dt.ndi.pmc.west <- dt.master.ndi.pmc %>% 
  select(Site.ID:no_death_lungc,
         -no_death_uri, -no_death_ards) %>% 
  inner_join(dt.pmc) %>% 
  inner_join(dt.ses) %>% 
  inner_join(dt.site) %>% 
  mutate(rW = ifelse(Region.IV == 1, 0,1),
         StrID = paste(age, sex, race)) %>% 
  select(-age, -sex, -race, -Region.IV) 
  
for (cmp in cmp.sub){
    dt.ndi.pmc.west[ ,paste0("rW_",cmp)] <- 
      dt.ndi.pmc.west[ ,cmp] * dt.ndi.pmc.west$rW
}

dt.ndi.pmc.west <- dt.ndi.pmc.west %>% 
  rename_at(vars(AS:ZN), ~paste("Yr", .x, sep = "_")) %>% 
  rename(SiteID = Site.ID) %>% 
  select(SiteID, Year, Month, StrID, rW, everything())

write.csv(dt.ndi.pmc.west, 
          file = here('data', 'processed', 'ndi-pmc-west.csv'),
          row.names = F)

### Midwest = 2
dt.ndi.pmc.midwest <- dt.master.ndi.pmc %>% 
  select(Site.ID:no_death_lungc,
         -no_death_uri, -no_death_ards) %>% 
  inner_join(dt.pmc) %>% 
  inner_join(dt.ses) %>% 
  inner_join(dt.site) %>% 
  mutate(rMW = ifelse(Region.IV == 2, 0,1),
         StrID = paste(age, sex, race)) %>% 
  select(-age, -sex, -race, -Region.IV) 
  
for (cmp in cmp.sub){
    dt.ndi.pmc.midwest[ ,paste0("rMW_",cmp)] <- 
      dt.ndi.pmc.midwest[ ,cmp] * dt.ndi.pmc.midwest$rMW
}

dt.ndi.pmc.midwest <- dt.ndi.pmc.midwest %>% 
  rename_at(vars(AS:ZN), ~paste("Yr", .x, sep = "_")) %>% 
  rename(SiteID = Site.ID) %>% 
  select(SiteID, Year, Month, StrID, rMW, everything())

write.csv(dt.ndi.pmc.midwest, 
          file = here('data', 'processed', 'ndi-pmc-midwest.csv'),
          row.names = F)

### South = 3
dt.ndi.pmc.south <- dt.master.ndi.pmc %>% 
  select(Site.ID:no_death_lungc,
         -no_death_uri, -no_death_ards) %>% 
  inner_join(dt.pmc) %>% 
  inner_join(dt.ses) %>% 
  inner_join(dt.site) %>% 
  mutate(rS = ifelse(Region.IV == 3, 0,1),
         StrID = paste(age, sex, race)) %>% 
  select(-age, -sex, -race, -Region.IV) 
  
for (cmp in cmp.sub){
    dt.ndi.pmc.south[ ,paste0("rS_",cmp)] <- 
      dt.ndi.pmc.south[ ,cmp] * dt.ndi.pmc.south$rS
}

dt.ndi.pmc.south <- dt.ndi.pmc.south %>% 
  rename_at(vars(AS:ZN), ~paste("Yr", .x, sep = "_")) %>% 
  rename(SiteID = Site.ID) %>% 
  select(SiteID, Year, Month, StrID, rS, everything())

write.csv(dt.ndi.pmc.south, 
          file = here('data', 'processed', 'ndi-pmc-south.csv'),
          row.names = F)

### Northeast = 4
dt.ndi.pmc.northeast <- dt.master.ndi.pmc %>% 
  select(Site.ID:no_death_lungc,
         -no_death_uri, -no_death_ards) %>% 
  inner_join(dt.pmc) %>% 
  inner_join(dt.ses) %>% 
  inner_join(dt.site) %>% 
  mutate(rNE = ifelse(Region.IV == 4, 0,1),
         StrID = paste(age, sex, race)) %>% 
  select(-age, -sex, -race, -Region.IV) 
  
for (cmp in cmp.sub){
    dt.ndi.pmc.northeast[ ,paste0("rNE_",cmp)] <- 
      dt.ndi.pmc.northeast[ ,cmp] * dt.ndi.pmc.northeast$rNE
}

dt.ndi.pmc.northeast <- dt.ndi.pmc.northeast %>% 
  rename_at(vars(AS:ZN), ~paste("Yr", .x, sep = "_")) %>% 
  rename(SiteID = Site.ID) %>% 
  select(SiteID, Year, Month, StrID, rNE, everything())

write.csv(dt.ndi.pmc.northeast, 
          file = here('data', 'processed', 'ndi-pmc-northeast.csv'),
          row.names = F)
```

```{r PMC Age}
cmp.sub <- c("AS", "CA", "CL", "NA", "NI", "NO3", "OC", 
             "PB", "PM", "SI", "SO4", "V", "ZN")

dt.pmc <- dt.pmc.1yr %>% 
  select(Site.ID, Year, Month, cmp.sub)

dt.ses <- dt.ses.site.bz12 %>% 
  mutate(ses = SES.Zip.Norm) %>% 
  select(Site.ID, Year, ses)

### Age 
dt.age <- dt.master.ndi.pmc %>%
  mutate(age = ifelse(age <= 75, "LE", "M")) %>% 
  select(Site.ID:no_death_lungc,
         -no_death_uri, -no_death_ards)

dt.age <- 
  aggregate(. ~ Site.ID + Year + Month + age + sex + race, dt.age, sum) %>%
  arrange(Site.ID, Year, Month, age, sex, race)

### LE 75
dt.ndi.pmc.ageLE75 <- dt.age %>% 
  inner_join(dt.pmc) %>% 
  inner_join(dt.ses) %>% 
  mutate(aLE75 = ifelse(age == "LE", 0,1),
         StrID = paste(age, sex, race)) %>% 
  select(-age, -sex, -race) 
  
for (cmp in cmp.sub){
    dt.ndi.pmc.ageLE75[ ,paste0("aLE75_",cmp)] <- 
      dt.ndi.pmc.ageLE75[ ,cmp] * dt.ndi.pmc.ageLE75$aLE75
}

dt.ndi.pmc.ageLE75 <- dt.ndi.pmc.ageLE75 %>% 
  rename_at(vars(AS:ZN), ~paste("Yr", .x, sep = "_")) %>% 
  rename(SiteID = Site.ID) %>% 
  select(SiteID, Year, Month, StrID, aLE75, everything())

write.csv(dt.ndi.pmc.ageLE75, 
          file = here('data', 'processed', 'ndi-pmc-ageLE75.csv'),
          row.names = F)

### M 75
dt.ndi.pmc.ageM75 <- dt.age %>% 
  inner_join(dt.pmc) %>% 
  inner_join(dt.ses) %>% 
  mutate(aM75 = ifelse(age == "M", 0,1),
         StrID = paste(age, sex, race)) %>% 
  select(-age, -sex, -race) 
  
for (cmp in cmp.sub){
    dt.ndi.pmc.ageM75[ ,paste0("aM75_",cmp)] <- 
      dt.ndi.pmc.ageM75[ ,cmp] * dt.ndi.pmc.ageM75$aM75
}

dt.ndi.pmc.ageM75 <- dt.ndi.pmc.ageM75 %>% 
  rename_at(vars(AS:ZN), ~paste("Yr", .x, sep = "_")) %>% 
  rename(SiteID = Site.ID) %>% 
  select(SiteID, Year, Month, StrID, aM75, everything())

write.csv(dt.ndi.pmc.ageM75, 
          file = here('data', 'processed', 'ndi-pmc-ageM75.csv'),
          row.names = F)
```

```{r PMC Sex}
cmp.sub <- c("AS", "CA", "CL", "NA", "NI", "NO3", "OC", 
             "PB", "PM", "SI", "SO4", "V", "ZN")

dt.pmc <- dt.pmc.1yr %>% 
  select(Site.ID, Year, Month, cmp.sub)

dt.ses <- dt.ses.site.bz12 %>% 
  mutate(ses = SES.Zip.Norm) %>% 
  select(Site.ID, Year, ses)

dt.sex <- dt.master.ndi.pmc %>% 
    select(Site.ID:no_death_lungc,
         -no_death_uri, -no_death_ards) %>%  
  inner_join(dt.pmc) %>% 
  inner_join(dt.ses)

### Female
dt.ndi.pmc.sexF <- dt.sex %>% 
  inner_join(dt.pmc) %>% 
  inner_join(dt.ses) %>% 
  mutate(sexF = ifelse(sex == "F", 0,1),
         StrID = paste(age, sex, race)) %>% 
  select(-age, -sex, -race) 
  
for (cmp in cmp.sub){
    dt.ndi.pmc.sexF[ ,paste0("sexF_",cmp)] <- 
      dt.ndi.pmc.sexF[ ,cmp] * dt.ndi.pmc.sexF$sexF
}

dt.ndi.pmc.sexF <- dt.ndi.pmc.sexF %>% 
  rename_at(vars(AS:ZN), ~paste("Yr", .x, sep = "_")) %>% 
  rename(SiteID = Site.ID) %>% 
  select(SiteID, Year, Month, StrID, sexF, everything())

write.csv(dt.ndi.pmc.sexF, 
          file = here('data', 'processed', 'ndi-pmc-sexF.csv'),
          row.names = F)

### Male
dt.ndi.pmc.sexM <- dt.sex %>% 
  inner_join(dt.pmc) %>% 
  inner_join(dt.ses) %>% 
  mutate(sexM = ifelse(sex == "M", 0,1),
         StrID = paste(age, sex, race)) %>% 
  select(-age, -sex, -race) 
  
for (cmp in cmp.sub){
    dt.ndi.pmc.sexM[ ,paste0("sexM_",cmp)] <- 
      dt.ndi.pmc.sexM[ ,cmp] * dt.ndi.pmc.sexM$sexM
}

dt.ndi.pmc.sexM <- dt.ndi.pmc.sexM %>% 
  rename_at(vars(AS:ZN), ~paste("Yr", .x, sep = "_")) %>% 
  rename(SiteID = Site.ID) %>% 
  select(SiteID, Year, Month, StrID, sexM, everything())

write.csv(dt.ndi.pmc.sexM, 
          file = here('data', 'processed', 'ndi-pmc-sexM.csv'),
          row.names = F)
```

```{r PMC BRFSS}
dt.pmc <- dt.pmc.1yr %>% 
  rename_at(vars(AS:ZN), ~paste("Yr", .x, sep = "_"))

dt.ses <- dt.ses.site.bz12 %>% 
  mutate(ses = SES.Zip.Norm) %>% 
  select(Site.ID, Year, ses)

dt.ndi.pmc.brfss <- dt.master.ndi.pmc %>% 
  mutate(StrID = paste(age, sex, race)) %>% 
  select(Site.ID, Year, Month, StrID, no_enrollee:no_death_kidn) %>%  
  inner_join(dt.pmc) %>% 
  inner_join(dt.ses) %>% 
  inner_join(dt.brfss.site) %>% 
  rename(SiteID = Site.ID)

write.csv(dt.ndi.pmc.brfss, 
          file = here('data', 'processed', 'ndi-pmc-brfss.csv'),
          row.names = F)
```

```{r PMC BZ 6}
cmp.sub <- c("AS", "CA", "CL", "NA", "NI", "NO3", "OC", 
             "PB", "PM", "SI", "SO4", "V", "ZN")

dt.pmc <- dt.pmc.1yr %>% 
  select(Site.ID, Year, Month, cmp.sub) %>% 
  rename_at(vars(AS:ZN), ~paste("Yr", .x, sep = "_"))

dt.ses <- dt.ses.site.bz6 %>% 
  mutate(ses = SES.Zip.Norm) %>% 
  select(Site.ID, Year, ses)

dt.ndi.pmc <- dt.master.ndi.pmc.bz6 %>% 
  mutate(StrID = paste(age, sex, race)) %>% 
  select(Site.ID, Year, Month, StrID, no_enrollee:no_death_lungc,
         -no_death_uri, -no_death_ards) %>% 
  inner_join(dt.pmc) %>% 
  inner_join(dt.ses) %>% 
  rename(SiteID = Site.ID)

write.csv(dt.ndi.pmc, 
          file = here('data', 'processed', 'ndi-pmc-bz6.csv'),
          row.names = F)
```

```{r PMC BZ 12}
cmp.sub <- c("AS", "CA", "CL", "NA", "NI", "NO3", "OC", 
             "PB", "PM", "SI", "SO4", "V", "ZN")

dt.pmc <- dt.pmc.1yr %>% 
  select(Site.ID, Year, Month, cmp.sub) %>% 
  rename_at(vars(AS:ZN), ~paste("Yr", .x, sep = "_"))

dt.ses <- dt.ses.site.bz12 %>% 
  mutate(ses = SES.Zip.Norm) %>% 
  select(Site.ID, Year, ses)

dt.ndi.pmc <- dt.master.ndi.pmc.bz12 %>% 
  mutate(StrID = paste(age, sex, race)) %>% 
  select(Site.ID, Year, Month, StrID, no_enrollee:no_death_lungc,
         -no_death_uri, -no_death_ards) %>% 
  inner_join(dt.pmc) %>% 
  inner_join(dt.ses) %>% 
  rename(SiteID = Site.ID)

write.csv(dt.ndi.pmc, 
          file = here('data', 'processed', 'ndi-pmc-bz12.csv'),
          row.names = F)
```

```{r PMC BZ 24}
cmp.sub <- c("AS", "CA", "CL", "NA", "NI", "NO3", "OC", 
             "PB", "PM", "SI", "SO4", "V", "ZN")

dt.pmc <- dt.pmc.1yr %>% 
  select(Site.ID, Year, Month, cmp.sub) %>% 
  rename_at(vars(AS:ZN), ~paste("Yr", .x, sep = "_"))

dt.ses <- dt.ses.site.bz24 %>% 
  mutate(ses = SES.Zip.Norm) %>% 
  select(Site.ID, Year, ses)

dt.ndi.pmc <- dt.master.ndi.pmc.bz24 %>% 
  mutate(StrID = paste(age, sex, race)) %>% 
  select(Site.ID, Year, Month, StrID, no_enrollee:no_death_lungc,
         -no_death_uri, -no_death_ards) %>% 
  inner_join(dt.pmc) %>% 
  inner_join(dt.ses) %>% 
  rename(SiteID = Site.ID)

write.csv(dt.ndi.pmc, 
          file = here('data', 'processed', 'ndi-pmc-bz24.csv'),
          row.names = F)
```

```{r PMC - 5yr}
dt.pmc <- dt.pmc.5yr %>% 
  rename_at(vars(AS:ZN), ~paste("Yr", .x, sep = "_"))

dt.ses <- dt.ses.site.bz12 %>% 
  mutate(ses = SES.Zip.Norm) %>% 
  select(Site.ID, Year, ses)

dt.ndi.pmc <- dt.master.ndi.pmc %>% 
  mutate(StrID = paste(age, sex, race)) %>% 
  select(Site.ID, Year, Month, StrID, no_enrollee:no_death_kidn) %>%  
  inner_join(dt.pmc) %>% 
  inner_join(dt.ses) %>% 
  rename(SiteID = Site.ID)

write.csv(dt.ndi.pmc, 
          file = here('data', 'processed', 'ndi-pmc-5yr.csv'),
          row.names = F)
```

```{r PMC - 4yr - 5yr}
dt.pmc <- dt.pmc.4yr.5yr %>% 
  rename_at(vars(AS:ZN), ~paste("Yr", .x, sep = "_"))

dt.ses <- dt.ses.site.bz12 %>% 
  mutate(ses = SES.Zip.Norm) %>% 
  select(Site.ID, Year, ses)

dt.ndi.pmc <- dt.master.ndi.pmc %>% 
  mutate(StrID = paste(age, sex, race)) %>% 
  select(Site.ID, Year, Month, StrID, no_enrollee:no_death_kidn) %>%  
  inner_join(dt.pmc) %>% 
  inner_join(dt.ses) %>% 
  rename(SiteID = Site.ID)

write.csv(dt.ndi.pmc, 
          file = here('data', 'processed', 'ndi-pmc-4yr-5yr.csv'),
          row.names = F)
```

```{r PMC - 3yr - 5yr}
dt.pmc <- dt.pmc.3yr.5yr %>% 
  rename_at(vars(AS:ZN), ~paste("Yr", .x, sep = "_"))

dt.ses <- dt.ses.site.bz12 %>% 
  mutate(ses = SES.Zip.Norm) %>% 
  select(Site.ID, Year, ses)

dt.ndi.pmc <- dt.master.ndi.pmc %>% 
  mutate(StrID = paste(age, sex, race)) %>% 
  select(Site.ID, Year, Month, StrID, no_enrollee:no_death_kidn) %>%  
  inner_join(dt.pmc) %>% 
  inner_join(dt.ses) %>% 
  rename(SiteID = Site.ID)

write.csv(dt.ndi.pmc, 
          file = here('data', 'processed', 'ndi-pmc-3yr-5yr.csv'),
          row.names = F)
```

```{r PMC - 2yr - 5yr}
dt.pmc <- dt.pmc.2yr.5yr %>% 
  rename_at(vars(AS:ZN), ~paste("Yr", .x, sep = "_"))

dt.ses <- dt.ses.site.bz12 %>% 
  mutate(ses = SES.Zip.Norm) %>% 
  select(Site.ID, Year, ses)

dt.ndi.pmc <- dt.master.ndi.pmc %>% 
  mutate(StrID = paste(age, sex, race)) %>% 
  select(Site.ID, Year, Month, StrID, no_enrollee:no_death_kidn) %>%  
  inner_join(dt.pmc) %>% 
  inner_join(dt.ses) %>% 
  rename(SiteID = Site.ID)

write.csv(dt.ndi.pmc, 
          file = here('data', 'processed', 'ndi-pmc-2yr-5yr.csv'),
          row.names = F)
```

```{r PMC - 1yr - 5yr}
dt.pmc <- dt.pmc.1yr.5yr %>% 
  rename_at(vars(AS:ZN), ~paste("Yr", .x, sep = "_"))

dt.ses <- dt.ses.site.bz12 %>% 
  mutate(ses = SES.Zip.Norm) %>% 
  select(Site.ID, Year, ses)

dt.ndi.pmc <- dt.master.ndi.pmc %>% 
  mutate(StrID = paste(age, sex, race)) %>% 
  select(Site.ID, Year, Month, StrID, no_enrollee:no_death_kidn) %>%  
  inner_join(dt.pmc) %>% 
  inner_join(dt.ses) %>% 
  rename(SiteID = Site.ID)

write.csv(dt.ndi.pmc, 
          file = here('data', 'processed', 'ndi-pmc-1yr-5yr.csv'),
          row.names = F)
```